roboptim::ResultWithWarnings Class Reference
roboptim::ResultWithWarnings Class Reference
Optimization problems
Represents the solution of an optimization problem when errors occurred during the solving process.
#include <roboptim/core/result-with-warnings.hh>
Public Member Functions
ResultWithWarnings (const Function::size_type inputSize, const Function::size_type outputSize=1) throw ()
Instantiate the class from an input/output size.
~ResultWithWarnings () throw ()
virtual std::ostream & print (std::ostream &o) const throw ()
Display the result on the specified output stream.
Public Attributes
std::vector< SolverWarning > warnings
Vector of warnings.
Detailed Description
Represents the solution of an optimization problem when errors occurred during the solving process.
This class is returned by a solver if a result has been found, but some problems happened.
A vector or warnings is provided in this result, otherwise the class behaves like Result.
Constructor & Destructor Documentation
roboptim::ResultWithWarnings::ResultWithWarnings (const Function::size_type inputSize, const Function::size_type outputSize = 1) throw () [explicit]
Instantiate the class from an input/output size.
Parameters:
inputSize input size
outputSize output size
roboptim::ResultWithWarnings::~ResultWithWarnings () throw ()
Member Function Documentation
std::ostream & roboptim::ResultWithWarnings::print (std::ostream & o) const throw () [virtual]
Display the result on the specified output stream.
Parameters:
o output stream used for display
Returns:
output stream
Reimplemented from roboptim::Result.
References roboptim::decindent(), roboptim::iendl(), roboptim::incindent(), and roboptim::Result::print().
Member Data Documentation
std::vector<SolverWarning> roboptim::ResultWithWarnings::warnings
Vector of warnings.
Each element of this vector is a potential problem that occurred during the optimization.