roboptim::GenericNumericLinearFunction< T > Class Template Reference
roboptim::GenericNumericLinearFunction< T > Class Template Reference
Mathematical functions
Build a linear function from a vector and a matrix.
#include <roboptim/core/numeric-linear-function.hh>
Public Member Functions
ROBOPTIM_TWICE_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericLinearFunction< T >)
GenericNumericLinearFunction (const matrix_t &A, const vector_t &b) throw ()
Build a linear function from a matrix and a vector.
~GenericNumericLinearFunction () throw ()
virtual std::ostream & print (std::ostream &) const throw ()
Display the function on the specified output stream.
const matrix_t & A () const
const vector_t & b () const
Protected Member Functions
void impl_compute (result_t &, const argument_t &) const throw ()
Function evaluation.
void impl_gradient (gradient_t &, const argument_t &, size_type=0) const throw ()
Gradient evaluation.
void impl_jacobian (jacobian_t &, const argument_t &) const throw ()
Jacobian evaluation.
Detailed Description
template<typename T>
class roboptim::GenericNumericLinearFunction< T >
Build a linear function from a vector and a matrix.
Implement a linear function using the general formula:
where and are set when the class is instantiated.
Examples:
numeric-linear-function.cc.
Constructor & Destructor Documentation
template<typename T > roboptim::GenericNumericLinearFunction< T >::GenericNumericLinearFunction (const matrix_t & A, const vector_t & b) throw ()
Build a linear function from a matrix and a vector.
See class documentation for A and b definition.
Parameters:
A A matrix
b b vector
template<typename T > roboptim::GenericNumericLinearFunction< T >::~GenericNumericLinearFunction () throw ()
Member Function Documentation
template<typename T > const matrix_t& roboptim::GenericNumericLinearFunction< T >::A () const [inline]
template<typename T > const vector_t& roboptim::GenericNumericLinearFunction< T >::b () const [inline]
template<typename T > void roboptim::GenericNumericLinearFunction< T >::impl_compute (result_t & result, const argument_t & argument) const throw () [protected, virtual]
Function evaluation.
Evaluate the function, has to be implemented in concrete classes.
Warning:
Do not call this function directly, call operator()(result_t&, const argument_t&) const throw () instead.
Parameters:
result result will be stored in this vector
argument point at which the function will be evaluated
Implements roboptim::GenericFunction< T >.
template<typename T > void roboptim::GenericNumericLinearFunction< T >::impl_gradient (gradient_t & gradient, const argument_t & argument, size_type functionId = 0) const throw () [protected, virtual]
Gradient evaluation.
Compute the gradient, has to be implemented in concrete classes. The gradient is computed for a specific sub-function which id is passed through the functionId argument.
Warning:
Do not call this function directly, call gradient instead.
Parameters:
gradient gradient will be store in this argument
argument point where the gradient will be computed
functionId evaluated function id in the split representation
Implements roboptim::GenericDifferentiableFunction< T >.
template<typename T > void roboptim::GenericNumericLinearFunction< T >::impl_jacobian (jacobian_t & jacobian, const argument_t & arg) const throw () [protected, virtual]
Jacobian evaluation.
Computes the jacobian, can be overridden by concrete classes. The default behavior is to compute the jacobian from the gradient.
Warning:
Do not call this function directly, call jacobian instead.
Parameters:
jacobian jacobian will be store in this argument
arg point where the jacobian will be computed
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
Reimplemented from roboptim::GenericDifferentiableFunction< T >.
template<typename T > std::ostream & roboptim::GenericNumericLinearFunction< T >::print (std::ostream & o) const throw () [virtual]
Display the function on the specified output stream.
Parameters:
o output stream used for display
Returns:
output stream
Reimplemented from roboptim::GenericLinearFunction< T >.
References roboptim::decindent(), roboptim::iendl(), and roboptim::incindent().
template<typename T > roboptim::GenericNumericLinearFunction< T >::ROBOPTIM_TWICE_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericLinearFunction< T >)