roboptim::finiteDifferenceGradientPolicies::Simple< T > Class Template Reference
roboptim::finiteDifferenceGradientPolicies::Simple< T > Class Template Reference
Fast finite difference gradient computation.
#include <roboptim/core/finite-difference-gradient.hh>
Public Member Functions
ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericDifferentiableFunction< T >)
void computeGradient (const GenericFunction< T > &adaptee, value_type epsilon, gradient_t &gradient, const argument_t &argument, size_type idFunction, argument_t &xEps) const throw ()
template<>
void computeGradient (const GenericFunction< EigenMatrixSparse > &adaptee, value_type epsilon, gradient_t &gradient, const argument_t &argument, size_type idFunction, argument_t &xEps) const throw()
Detailed Description
template<typename T>
class roboptim::finiteDifferenceGradientPolicies::Simple< T >
Fast finite difference gradient computation.
Finite difference is computed using forward difference.
Examples:
finite-difference-gradient.cc.
Member Function Documentation
template<typename T > void roboptim::finiteDifferenceGradientPolicies::Simple< T >::computeGradient (const GenericFunction< T > & adaptee, value_type epsilon, gradient_t & gradient, const argument_t & argument, size_type idFunction, argument_t & xEps) const throw ()
References roboptim::GenericFunction< T >::inputSize(), and roboptim::GenericFunction< T >::outputSize().
template<> void roboptim::finiteDifferenceGradientPolicies::Simple< EigenMatrixSparse >::computeGradient (const GenericFunction< EigenMatrixSparse > & adaptee, value_type epsilon, gradient_t & gradient, const argument_t & argument, size_type idFunction, argument_t & xEps) const throw() [inline]
References roboptim::GenericFunction< T >::inputSize(), and roboptim::GenericFunction< T >::outputSize().
template<typename T > roboptim::finiteDifferenceGradientPolicies::Simple< T >::ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericDifferentiableFunction< T >)