roboptim::GenericTwiceDifferentiableFunction< T > Class Template Reference
roboptim::GenericTwiceDifferentiableFunction< T > Class Template Reference
Mathematical abstract functions
Define an abstract function which is derivable twice ().
#include <roboptim/core/twice-differentiable-function.hh>
Public Types
typedef matrix_t hessian_t
Hessian type.
typedef std::pair< size_type,
size_type > hessianSize_t
Hessian size type represented as a pair of values.
Public Member Functions
ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericDifferentiableFunction< T >)
hessianSize_t hessianSize () const throw ()
Return the size of a hessian.
bool isValidHessian (const hessian_t &hessian) const throw ()
Check if the hessian is valid (check sizes).
hessian_t hessian (const argument_t &argument, size_type functionId=0) const throw ()
Compute the hessian at a given point.
void hessian (hessian_t &hessian, const argument_t &argument, size_type functionId=0) const throw ()
Compute the hessian at a given point.
virtual std::ostream & print (std::ostream &) const throw ()
Display the function on the specified output stream.
Protected Member Functions
GenericTwiceDifferentiableFunction (size_type inputSize, size_type outputSize=1, std::string name=std::string()) throw ()
Concrete class constructor should call this constructor.
virtual void impl_hessian (hessian_t &hessian, const argument_t &argument, size_type functionId=0) const =0 throw ()
Hessian evaluation.
void setZero (hessian_t &symmetric) const
Set a symmetric matrix to zero.
Detailed Description
template<typename T>
class roboptim::GenericTwiceDifferentiableFunction< T >
Define an abstract function which is derivable twice ().
A twice derivable function is a derivable function which provides a way to compute its hessian.
, where is the input size and is the output size.
Hessian computation is done through the impl_hessian method that has to implemented by the concrete class inheriting this class.
The hessian of a function where and is a tensor. To avoid this costly representation, the function is split into functions. See #DifferentialeFunction documentation for more information.
Member Typedef Documentation
template<typename T > typedef matrix_t roboptim::GenericTwiceDifferentiableFunction< T >::hessian_t
Hessian type.
Hessians are symmetric matrices.
Reimplemented in roboptim::GenericLinearFunction< T >.
template<typename T > typedef std::pair<size_type, size_type> roboptim::GenericTwiceDifferentiableFunction< T >::hessianSize_t
Hessian size type represented as a pair of values.
Constructor & Destructor Documentation
template<typename T > roboptim::GenericTwiceDifferentiableFunction< T >::GenericTwiceDifferentiableFunction (size_type inputSize, size_type outputSize = 1, std::string name = std::string ()) throw () [protected]
Concrete class constructor should call this constructor.
Parameters:
inputSize input size (argument size)
outputSize output size (result size)
name function's name
Member Function Documentation
template<typename T > hessian_t roboptim::GenericTwiceDifferentiableFunction< T >::hessian (const argument_t & argument, size_type functionId = 0) const throw () [inline]
Compute the hessian at a given point.
Program will abort if the argument size is wrong.
Parameters:
argument point where the hessian will be computed
functionId evaluated function id in the split representation
Returns:
computed hessian
Examples:
numeric-quadratic-function.cc.
References roboptim::GenericTwiceDifferentiableFunction< T >::hessianSize(), and roboptim::GenericTwiceDifferentiableFunction< T >::setZero().
Referenced by roboptim::GenericTwiceDifferentiableFunction< T >::isValidHessian().
template<typename T > void roboptim::GenericTwiceDifferentiableFunction< T >::hessian (hessian_t & hessian, const argument_t & argument, size_type functionId = 0) const throw () [inline]
Compute the hessian at a given point.
Program will abort if the argument size is wrong.
Parameters:
hessian hessian will be stored here
argument point where the hessian will be computed
functionId evaluated function id in the split representation
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
References roboptim::GenericTwiceDifferentiableFunction< T >::impl_hessian(), roboptim::GenericTwiceDifferentiableFunction< T >::isValidHessian(), and roboptim::GenericFunction< T >::logger.
template<typename T > hessianSize_t roboptim::GenericTwiceDifferentiableFunction< T >::hessianSize () const throw () [inline]
Return the size of a hessian.
Hessian size is equales to (input size, input size).
Returns:
hessian's size as a pair
References roboptim::GenericFunction< T >::inputSize().
Referenced by roboptim::GenericTwiceDifferentiableFunction< T >::hessian(), and roboptim::GenericTwiceDifferentiableFunction< T >::isValidHessian().
template<typename T > virtual void roboptim::GenericTwiceDifferentiableFunction< T >::impl_hessian (hessian_t & hessian, const argument_t & argument, size_type functionId = 0) const throw () [protected, pure virtual]
Hessian evaluation.
Compute the hessian, has to be implemented in concrete classes. The hessian is computed for a specific sub-function which id is passed through the functionId argument.
Warning:
Do not call this function directly, call hessian instead.
Parameters:
hessian hessian will be stored here
argument point where the hessian will be computed
functionId evaluated function id in the split representation
Implemented in roboptim::NTimesDerivableFunction< 2 >, roboptim::NumericQuadraticFunction, and roboptim::GenericLinearFunction< T >.
Referenced by roboptim::GenericTwiceDifferentiableFunction< T >::hessian().
template<typename T > bool roboptim::GenericTwiceDifferentiableFunction< T >::isValidHessian (const hessian_t & hessian) const throw () [inline]
Check if the hessian is valid (check sizes).
Parameters:
hessian hessian that will be checked
Returns:
true if valid, false if not
References roboptim::GenericTwiceDifferentiableFunction< T >::hessian(), and roboptim::GenericTwiceDifferentiableFunction< T >::hessianSize().
Referenced by roboptim::GenericTwiceDifferentiableFunction< T >::hessian().
template<typename T > std::ostream & roboptim::GenericTwiceDifferentiableFunction< T >::print (std::ostream & o) const throw () [virtual]
Display the function on the specified output stream.
Parameters:
o output stream used for display
Returns:
output stream
Reimplemented from roboptim::GenericDifferentiableFunction< T >.
Reimplemented in roboptim::NTimesDerivableFunction< 2 >, roboptim::GenericLinearFunction< T >, roboptim::NumericQuadraticFunction, roboptim::GenericNumericLinearFunction< T >, roboptim::GenericQuadraticFunction< T >, roboptim::IdentityFunction, and roboptim::ConstantFunction.
References roboptim::indent().
template<typename T > roboptim::GenericTwiceDifferentiableFunction< T >::ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericDifferentiableFunction< T >)
template<typename T > void roboptim::GenericTwiceDifferentiableFunction< T >::setZero (hessian_t & symmetric) const [inline, protected]
Set a symmetric matrix to zero.
Note:
there might be an eigen function to do that.
Referenced by roboptim::GenericTwiceDifferentiableFunction< T >::hessian().