roboptim Namespace Reference
roboptim Namespace Reference
Meta-functions, functions and solvers related classes.
Namespaces
namespace detail
namespace fg
namespace finiteDifferenceGradientPolicies
Contains finite difference gradients policies.
namespace visualization
Graphic visualization.
Classes
class ConstantFunction
Constant function.
class DerivableParametrizedFunction
Parametrized function with parameter derivative available.
struct derivativeSize< Function >
struct derivativeSize< DifferentiableFunction >
struct derivativeSize< TwiceDifferentiableFunction >
struct derivativeSize< NTimesDerivableFunction< N > >
class GenericDifferentiableFunction
Define an abstract derivable function ().
struct ltvector
class CachedFunction
class Split
class BadGradient
Exception thrown when a gradient check fail.
class FiniteDifferenceGradient
Compute automatically a gradient with finite differences.
struct GenericFunctionTraits
GenericFunction traits.
class GenericFunction
Define an abstract mathematical function ().
struct GenericFunctionTraits< EigenMatrixDense >
Trait specializing GenericFunction for Eigen dense matrices.
struct GenericFunctionTraits< EigenMatrixSparse >
Trait specializing GenericFunction for Eigen sparse matrices.
class NoSolution
Tag a result if no solution has been found.
struct EigenMatrixDense
Tag type for functions using Eigen dense matrices.
struct EigenMatrixSparse
Tag type for functions using Eigen sparse matrices.
class GenericSolver
Abstract interface satisfied by all solvers.
class IdentityFunction
Identity function.
class GenericLinearFunction
Define an abstract linear function.
class NTimesDerivableFunction< 2 >
Explicit specialization for the stop case of NTimesDerivable class.
class NTimesDerivableFunction
Define a function, derivable n times ().
class NumericLinearFunction
Build a linear function from a vector and a matrix.
class NumericQuadraticFunction
Build a quadratic function from a matrix and a vector.
class ParametrizedFunction
Define an abstract parametrized mathematical function ().
class DummySolverLastState
Dummy solver which always fails, but returns the last state of the solver.
class DummySolver
Dummy solver which always fails.
class Problem< F, boost::mpl::vector<> >
class Problem
class GenericQuadraticFunction
Define an abstract quadratic function.
class ResultWithWarnings
Represents the solution of an optimization problem when errors occurred during the solving process.
class Result
Represents the solution of an optimization problem.
class SolverError
Base exception class for solving errors.
class SolverFactory
Define a solver factory that instanciate the plug-ins.
class SolverWarning
Exception used for non-critical errors during optimization.
struct Parameter
Parameters type.
class Solver
Solver for a specific problem class.
class SumOfC1Squares
Sum of the squares of differentiable functions.
class GenericTwiceDifferentiableFunction
Define an abstract function which is derivable twice ().
Typedefs
typedef DifferentiableFunction DerivableFunction
Legacy name of TwiceDifferentiableFunction.
typedef GenericFunction
< EigenMatrixDense > Function
Dense function.
typedef GenericFunction
< EigenMatrixSparse > SparseFunction
Sparse function.
typedef
GenericDifferentiableFunction
< EigenMatrixDense > DifferentiableFunction
Dense differentiable function.
typedef
GenericDifferentiableFunction
< EigenMatrixSparse > DifferentiableSparseFunction
Sparse differentiable function.
typedef
GenericTwiceDifferentiableFunction
< EigenMatrixDense > TwiceDifferentiableFunction
typedef
GenericTwiceDifferentiableFunction
< EigenMatrixSparse > TwiceDifferentiableSparseFunction
typedef GenericLinearFunction
< EigenMatrixDense > LinearFunction
typedef GenericLinearFunction
< EigenMatrixSparse > LinearSparseFunction
typedef
GenericQuadraticFunction
< EigenMatrixDense > QuadraticFunction
typedef
GenericQuadraticFunction
< EigenMatrixSparse > QuadraticSparseFunction
typedef TwiceDifferentiableFunction TwiceDerivableFunction
Legacy name of DifferentiableFunction.
Functions
template<typename P , typename C >
void addNonScalarConstraint (P &problem, boost::shared_ptr< C > constraint, std::vector< Function::interval_t > interval, std::vector< Function::value_type > scale=std::vector< Function::value_type >()) throw (std::runtime_error)
ROBOPTIM_DLLAPI std::ostream & operator<< (std::ostream &o, const BadGradient &f)
Override operator<< to handle exception display.
ROBOPTIM_DLLAPI bool checkGradient (const DifferentiableFunction &function, Function::size_type functionId, const Function::vector_t &x, Function::value_type threshold=finiteDifferenceThreshold) throw ()
Check if a gradient is valid.
ROBOPTIM_DLLAPI void checkGradientAndThrow (const DifferentiableFunction &function, Function::size_type functionId, const Function::vector_t &x, Function::value_type threshold=finiteDifferenceThreshold) throw (BadGradient)
template<typename T >
std::ostream & operator<< (std::ostream &o, const GenericFunction< T > &f)
Override operator<< to handle function display.
ROBOPTIM_DLLAPI std::ostream & operator<< (std::ostream &o, const GenericSolver &gs)
Override operator<< to handle solver display.
ROBOPTIM_DLLAPI std::ostream & operator<< (std::ostream &o, const NoSolution &ns)
Override operator<< to display ``no solution'' objects.
ROBOPTIM_DLLAPI long int & indent (std::ostream &o)
The current indentation level for o.
ROBOPTIM_DLLAPI std::ostream & incindent (std::ostream &o)
Increment the indentation.
ROBOPTIM_DLLAPI std::ostream & decindent (std::ostream &o)
Decrement the indentation.
ROBOPTIM_DLLAPI std::ostream & resetindent (std::ostream &o)
Reset the indentation.
ROBOPTIM_DLLAPI std::ostream & iendl (std::ostream &o)
Print an end of line, then set the indentation.
ROBOPTIM_DLLAPI std::ostream & incendl (std::ostream &o)
Increment the indentation, print an end of line, and set the indentation.
ROBOPTIM_DLLAPI std::ostream & decendl (std::ostream &o)
Decrement the indentation, print an end of line, and set the indentation.
template<typename F >
std::ostream & operator<< (std::ostream &o, const ParametrizedFunction< F > &f)
Override operator<< to handle function display.
template<typename F >
std::ostream & operator<< (std::ostream &o, const Problem< F, boost::mpl::vector<> > &pb)
Override operator<< to handle problem display.
template<typename F , typename CLIST >
std::ostream & operator<< (std::ostream &o, const Problem< F, CLIST > &pb)
Override operator<< to handle problem display.
ROBOPTIM_DLLAPI std::ostream & operator<< (std::ostream &o, const Result &r)
Override operator<< to handle result display.
ROBOPTIM_DLLAPI std::ostream & operator<< (std::ostream &o, const SolverError &e)
Override operator<< to handle error display.
template<typename T >
T * unionCast (void *ptr)
ROBOPTIM_DLLAPI std::ostream & operator<< (std::ostream &o, const Parameter &parameter)
Override operator<< to display ``parameters'' objects.
template<typename T >
std::ostream & operator<< (std::ostream &, const std::vector< T > &)
Display a vector.
template<typename T1 , typename T2 >
std::ostream & operator<< (std::ostream &, const std::pair< T1, T2 > &)
Display a pair.
template<typename T >
std::ostream & operator<< (std::ostream &, const Eigen::MatrixBase< T > &)
Display an Eigen object with the appropriate IOFormat.
Variables
static const double finiteDifferenceThreshold = 1e-4
Default threshold for checkGradient.
static const double finiteDifferenceEpsilon = 1e-8
Default epsilon for finite difference class.
Detailed Description
Meta-functions, functions and solvers related classes.
Typedef Documentation
typedef DifferentiableFunction roboptim::DerivableFunction
Legacy name of TwiceDifferentiableFunction.
typedef GenericDifferentiableFunction<EigenMatrixDense> roboptim::DifferentiableFunction
Dense differentiable function.
Examples:
finite-difference-gradient.cc, and problem-cc.cc.
typedef GenericDifferentiableFunction<EigenMatrixSparse> roboptim::DifferentiableSparseFunction
Sparse differentiable function.
typedef GenericFunction<EigenMatrixDense> roboptim::Function
Dense function.
Examples:
visualization-gnuplot-function.cc.
typedef GenericLinearFunction<EigenMatrixDense> roboptim::LinearFunction
typedef GenericLinearFunction<EigenMatrixSparse> roboptim::LinearSparseFunction
typedef GenericQuadraticFunction<EigenMatrixDense> roboptim::QuadraticFunction
typedef GenericQuadraticFunction<EigenMatrixSparse> roboptim::QuadraticSparseFunction
typedef GenericFunction<EigenMatrixSparse> roboptim::SparseFunction
Sparse function.
typedef TwiceDifferentiableFunction roboptim::TwiceDerivableFunction
Legacy name of DifferentiableFunction.
typedef GenericTwiceDifferentiableFunction<EigenMatrixDense> roboptim::TwiceDifferentiableFunction
typedef GenericTwiceDifferentiableFunction<EigenMatrixSparse> roboptim::TwiceDifferentiableSparseFunction
Function Documentation
std::ostream & roboptim::decendl (std::ostream & o)
Decrement the indentation, print an end of line, and set the indentation.
References decindent(), and iendl().
std::ostream & roboptim::decindent (std::ostream & o)
Decrement the indentation.
References indent().
Referenced by decendl(), roboptim::detail::printConstraint< P >::operator()(), roboptim::ConstantFunction::print(), roboptim::IdentityFunction::print(), roboptim::NumericLinearFunction::print(), roboptim::NumericQuadraticFunction::print(), roboptim::BadGradient::print(), roboptim::Result::print(), roboptim::ResultWithWarnings::print(), roboptim::Solver< F, C >::print(), roboptim::Problem< F, boost::mpl::vector<> >::print(), and roboptim::Problem< F, CLIST >::print().
std::ostream & roboptim::iendl (std::ostream & o)
Print an end of line, then set the indentation.
References indent().
Referenced by decendl(), incendl(), roboptim::detail::printConstraint< P >::operator()(), roboptim::ConstantFunction::print(), roboptim::IdentityFunction::print(), roboptim::NumericLinearFunction::print(), roboptim::NumericQuadraticFunction::print(), roboptim::BadGradient::print(), roboptim::Result::print(), roboptim::ResultWithWarnings::print(), roboptim::Solver< F, C >::print(), roboptim::Problem< F, boost::mpl::vector<> >::print(), and roboptim::Problem< F, CLIST >::print().
std::ostream & roboptim::incendl (std::ostream & o)
Increment the indentation, print an end of line, and set the indentation.
References iendl(), and incindent().
Referenced by roboptim::Problem< F, boost::mpl::vector<> >::print(), and roboptim::Problem< F, CLIST >::print().
std::ostream & roboptim::incindent (std::ostream & o)
Increment the indentation.
References indent().
Referenced by incendl(), roboptim::detail::printConstraint< P >::operator()(), roboptim::ConstantFunction::print(), roboptim::IdentityFunction::print(), roboptim::NumericLinearFunction::print(), roboptim::NumericQuadraticFunction::print(), roboptim::BadGradient::print(), roboptim::Result::print(), roboptim::ResultWithWarnings::print(), and roboptim::Solver< F, C >::print().
long int & roboptim::indent (std::ostream & o)
The current indentation level for o.
Referenced by decindent(), iendl(), incindent(), roboptim::GenericTwiceDifferentiableFunction< T >::print(), roboptim::GenericDifferentiableFunction< T >::print(), roboptim::GenericFunction< T >::print(), and resetindent().
template<typename T > std::ostream & roboptim::operator<< (std::ostream & o, const std::vector< T > & vect)
Display a vector.
template<typename T1 , typename T2 > std::ostream & roboptim::operator<< (std::ostream & o, const std::pair< T1, T2 > & p)
Display a pair.
template<typename T > std::ostream & roboptim::operator<< (std::ostream & o, const Eigen::MatrixBase< T > & matrix)
Display an Eigen object with the appropriate IOFormat.
std::ostream & roboptim::operator<< (std::ostream & o, const BadGradient & f)
Override operator<< to handle exception display.
Parameters:
o output stream used for display
f function to be displayed
Returns:
output stream
References roboptim::BadGradient::print().
std::ostream & roboptim::operator<< (std::ostream & o, const Result & r)
Override operator<< to handle result display.
Parameters:
o output stream used for display
r result to be displayed
Returns:
output stream
References roboptim::Result::print().
std::ostream & roboptim::operator<< (std::ostream & o, const SolverError & e)
Override operator<< to handle error display.
Parameters:
o output stream used for display
e error to be displayed
Returns:
output stream
References roboptim::SolverError::print().
template<typename F > std::ostream & roboptim::operator<< (std::ostream & o, const ParametrizedFunction< F > & f)
Override operator<< to handle function display.
Parameters:
o output stream used for display
f function to be displayed
Returns:
output stream
std::ostream & roboptim::operator<< (std::ostream & o, const GenericSolver & gs)
Override operator<< to handle solver display.
Parameters:
o output stream used for display
gs solver to be displayed
Returns:
output stream
References roboptim::GenericSolver::print().
std::ostream & roboptim::operator<< (std::ostream & o, const NoSolution & ns)
Override operator<< to display ``no solution'' objects.
Parameters:
o output stream used for display
ns NoSolution object, ignored
Returns:
output stream
std::ostream & roboptim::resetindent (std::ostream & o)
Reset the indentation.
References indent().
template<typename T > T* roboptim::unionCast (void * ptr)
Variable Documentation
const double roboptim::finiteDifferenceEpsilon = 1e-8 [static]
Default epsilon for finite difference class.
const double roboptim::finiteDifferenceThreshold = 1e-4 [static]
Default threshold for checkGradient.