#! /bin/sh

# Print an error message and exit.
die ()
{
    echo >&2 "fatal: $1"
    exit 2
}

# Properly explain how to set up a RobOptim working directory and exit.
die_nosourceforgealias ()
{
    echo >&2 "To properly finish setting up your working directory,"
    echo >&2 "you need to define how RobOptim should connect to SourceForge."
    echo >&2 ""
    echo >&2 "If you only need read-access (which is usually what one wants):"
    echo >&2 "echo '[url \"git://roboptim.git.sourceforge.net/gitroot/\"]"
    echo >&2 "        insteadOf = sourceforge:' >> ~/.gitconfig"
    echo >&2 ""

    die "no \`\`sourceforge:'' alias in your git configuration."
}

# Make sure that the submodule are retrieved.
if test -d ".git"; then
    if test x`git config -l | grep 'url\..*\.insteadof=sourceforge:'` = x; then
	die_nosourceforgealias
    fi

    git submodule init
    git submodule update
fi

exec build-aux/bootstrap
