roboptim::visualization::Gnuplot Class Reference
roboptim::visualization::Gnuplot Class Reference
Visualization
Gnuplot script.
#include <roboptim/core/visualization/gnuplot.hh>
Public Member Functions
~Gnuplot ()
void push_command (gnuplot::Command cmd)
Add a new Gnuplot command to the script.
std::ostream & print (std::ostream &) const
Display the Gnuplot script on the specified output stream.
Gnuplot & operator<< (gnuplot::Command)
void clear ()
Clear the vector of commands.
Static Public Member Functions
static Gnuplot make_gnuplot (bool with_header=true)
Instanciate a Gnuplot without setting a term.
static Gnuplot make_interactive_gnuplot (bool with_header=true)
Instanciate a Gnuplot suitable for interactive use.
Protected Member Functions
Gnuplot (bool with_header=true)
Default constructor can not be called directly.
Detailed Description
Gnuplot script.
This class gathers Gnuplot commands to build a complete Gnuplot script. Gnuplot commands can be inserted through this object through the << operator and this object can be put into an output stream using the << operator.
Examples:
visualization-gnuplot-function.cc, and visualization-gnuplot-simple.cc.
Constructor & Destructor Documentation
roboptim::visualization::Gnuplot::~Gnuplot ()
roboptim::visualization::Gnuplot::Gnuplot (bool with_header = true) [explicit, protected]
Default constructor can not be called directly.
Use of the named constructor (see static methods) to instantiate this class.
References roboptim::visualization::gnuplot::comment(), and push_command().
Member Function Documentation
void roboptim::visualization::Gnuplot::clear ()
Clear the vector of commands.
static Gnuplot roboptim::visualization::Gnuplot::make_gnuplot (bool with_header = true) [inline, static]
Instanciate a Gnuplot without setting a term.
Parameters:
with_header whether to print the header or not
Returns:
Gnuplot instance
static Gnuplot roboptim::visualization::Gnuplot::make_interactive_gnuplot (bool with_header = true) [inline, static]
Instanciate a Gnuplot suitable for interactive use.
This initializes a persistent Gnuplot instance which is suitable for user interaction.
Parameters:
with_header whether to print the header or not
Returns:
Gnuplot instance
References push_command(), and roboptim::visualization::gnuplot::set().
Gnuplot & roboptim::visualization::Gnuplot::operator<< (gnuplot::Command cmd)
References push_command().
std::ostream & roboptim::visualization::Gnuplot::print (std::ostream & o) const
Display the Gnuplot script on the specified output stream.
Parameters:
o output stream used for display
Returns:
output stream
Referenced by roboptim::visualization::operator<<().
void roboptim::visualization::Gnuplot::push_command (gnuplot::Command cmd)
Add a new Gnuplot command to the script.
Parameters:
cmd command that will be pushed
Referenced by Gnuplot(), make_interactive_gnuplot(), operator<<(), and roboptim::visualization::operator<<().