roboptim::GenericIdentityFunction< T > Class Template Reference
roboptim::GenericIdentityFunction< T > Class Template Reference
Mathematical functions
Identity function.
#include <roboptim/core/function/identity.hh>
Public Member Functions
ROBOPTIM_TWICE_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericLinearFunction< T >)
GenericIdentityFunction (const_vector_ref offset)
Build an identity function.
~GenericIdentityFunction ()
virtual std::ostream & print (std::ostream &o) const
Display the function on the specified output stream.
Protected Member Functions
void impl_compute (result_ref result, const_argument_ref argument) const
Function evaluation.
void impl_jacobian (jacobian_ref jacobian, const_argument_ref) const
Jacobian evaluation.
void impl_gradient (gradient_ref gradient, const_argument_ref, size_type idFunction) const
Gradient evaluation.
template<>
void impl_gradient (gradient_ref gradient, const_argument_ref, size_type idFunction) const
Gradient evaluation.
Detailed Description
template<typename T>
class roboptim::GenericIdentityFunction< T >
Identity function.
Implement a linear function using the formula:
\[f(x) = x + offset\]
where \(A\) and \(b\) are set when the class is instantiated.
Constructor & Destructor Documentation
template<typename T > roboptim::GenericIdentityFunction< T >::GenericIdentityFunction (const_vector_ref offset) [inline]
Build an identity function.
Parameters:
offset identity function offset
template<typename T > roboptim::GenericIdentityFunction< T >::~GenericIdentityFunction () [inline]
Member Function Documentation
template<typename T > void roboptim::GenericIdentityFunction< T >::impl_compute (result_ref result, const_argument_ref argument) const [inline, protected, virtual]
Function evaluation.
Evaluate the function, has to be implemented in concrete classes.
Warning:
Do not call this function directly, call operator()(result_ref, const_argument_ref) const instead.
Parameters:
result result will be stored in this vector
argument point at which the function will be evaluated
Implements roboptim::GenericFunction< T >.
template<> void roboptim::GenericIdentityFunction< EigenMatrixSparse >::impl_gradient (gradient_ref gradient, const_argument_ref argument, size_type functionId) const [inline, protected, virtual]
Gradient evaluation.
Compute the gradient, has to be implemented in concrete classes. The gradient is computed for a specific sub-function which id is passed through the functionId argument.
Warning:
Do not call this function directly, call gradient instead.
Parameters:
gradient gradient will be store in this argument
argument point where the gradient will be computed
functionId evaluated function id in the split representation
Implements roboptim::GenericDifferentiableFunction< T >.
template<typename T > void roboptim::GenericIdentityFunction< T >::impl_jacobian (jacobian_ref jacobian, const_argument_ref arg) const [inline, protected, virtual]
Jacobian evaluation.
Computes the jacobian, can be overridden by concrete classes. The default behavior is to compute the jacobian from the gradient.
Warning:
Do not call this function directly, call jacobian instead.
Parameters:
jacobian jacobian will be store in this argument
arg point where the jacobian will be computed
Reimplemented from roboptim::GenericDifferentiableFunction< T >.
template<typename T > virtual std::ostream& roboptim::GenericIdentityFunction< T >::print (std::ostream & o) const [inline, virtual]
Display the function on the specified output stream.
Parameters:
o output stream used for display
Returns:
output stream
Reimplemented from roboptim::GenericLinearFunction< T >.
References roboptim::decindent(), roboptim::iendl(), and roboptim::incindent().
template<typename T > roboptim::GenericIdentityFunction< T >::ROBOPTIM_TWICE_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericLinearFunction< T >)