roboptim::GenericFiniteDifferenceGradient< T, FdgPolicy > Class Template Reference
roboptim::GenericFiniteDifferenceGradient< T, FdgPolicy > Class Template Reference
Function decorators
Compute automatically a gradient with finite differences.
#include <roboptim/core/decorator/finite-difference-gradient.hh>
Public Member Functions
ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericDifferentiableFunction< T >)
GenericFiniteDifferenceGradient (const boost::shared_ptr< const GenericFunction< T > > &f, value_type e=finiteDifferenceEpsilon)
Instantiate a finite differences gradient.
GenericFiniteDifferenceGradient (const GenericFunction< T > &f, value_type e=finiteDifferenceEpsilon) ROBOPTIM_CORE_DEPRECATED
Instantiate a finite differences gradient.
~GenericFiniteDifferenceGradient ()
virtual std::ostream & print (std::ostream &o) const
Display the function on the specified output stream.
Protected Member Functions
virtual void impl_compute (result_ref, const_argument_ref) const
Function evaluation.
virtual void impl_gradient (gradient_ref, const_argument_ref argument, size_type=0) const
Gradient evaluation.
virtual void impl_jacobian (jacobian_ref jacobian, const_argument_ref argument) const
Jacobian evaluation.
std::string generateName (const GenericFunction< T > &adaptee) const
Protected Attributes
const boost::shared_ptr< const
GenericFunction< T > > adaptee_
Shared pointer to the wrapped function.
const value_type epsilon_
argument_t xEps_
Detailed Description
template<typename T, typename FdgPolicy>
class roboptim::GenericFiniteDifferenceGradient< T, FdgPolicy >
Compute automatically a gradient with finite differences.
Finite difference gradient is a method to approximate a function's gradient. It is particularly useful in RobOptim to avoid the need to compute the analytical gradient manually.
This class takes a Function as its input and wraps it into a derivable function.
The one dimensional formula is:
\[f'(x)\approx {f(x+\epsilon)-f(x)\over \epsilon}\]
where \(\epsilon\) is a constant given when calling the class constructor.
Constructor & Destructor Documentation
template<typename T, typename FdgPolicy> roboptim::GenericFiniteDifferenceGradient< T, FdgPolicy >::GenericFiniteDifferenceGradient (const boost::shared_ptr< const GenericFunction< T > > & f, value_type e = finiteDifferenceEpsilon)
Instantiate a finite differences gradient.
Instantiate a derivable function that will wrap a non derivable function and compute automatically its gradient using finite differences.
Parameters:
f shared pointer to the function that will be wrapped.
e epsilon used in finite difference computation
template<typename T, typename FdgPolicy> roboptim::GenericFiniteDifferenceGradient< T, FdgPolicy >::GenericFiniteDifferenceGradient (const GenericFunction< T > & f, value_type e = finiteDifferenceEpsilon)
Instantiate a finite differences gradient.
WARNING: deprecated version. Prefer the shared_ptr alternative.
Instantiate a derivable function that will wrap a non derivable function and compute automatically its gradient using finite differences.
Parameters:
f function that will e wrapped
e epsilon used in finite difference computation
template<typename T , typename FdgPolicy > roboptim::GenericFiniteDifferenceGradient< T, FdgPolicy >::~GenericFiniteDifferenceGradient ()
Member Function Documentation
template<typename T , typename FdgPolicy > std::string roboptim::GenericFiniteDifferenceGradient< T, FdgPolicy >::generateName (const GenericFunction< T > & adaptee) const [protected]
References roboptim::GenericFunction< T >::getName().
template<typename T , typename FdgPolicy > void roboptim::GenericFiniteDifferenceGradient< T, FdgPolicy >::impl_compute (result_ref result, const_argument_ref argument) const [protected, virtual]
Function evaluation.
Evaluate the function, has to be implemented in concrete classes.
Warning:
Do not call this function directly, call operator()(result_ref, const_argument_ref) const instead.
Parameters:
result result will be stored in this vector
argument point at which the function will be evaluated
Implements roboptim::GenericFunction< T >.
template<typename T , typename FdgPolicy > void roboptim::GenericFiniteDifferenceGradient< T, FdgPolicy >::impl_gradient (gradient_ref gradient, const_argument_ref argument, size_type functionId = 0) const [protected, virtual]
Gradient evaluation.
Compute the gradient, has to be implemented in concrete classes. The gradient is computed for a specific sub-function which id is passed through the functionId argument.
Warning:
Do not call this function directly, call gradient instead.
Parameters:
gradient gradient will be store in this argument
argument point where the gradient will be computed
functionId evaluated function id in the split representation
Implements roboptim::GenericDifferentiableFunction< T >.
template<typename T , typename FdgPolicy > void roboptim::GenericFiniteDifferenceGradient< T, FdgPolicy >::impl_jacobian (jacobian_ref jacobian, const_argument_ref arg) const [protected, virtual]
Jacobian evaluation.
Computes the jacobian, can be overridden by concrete classes. The default behavior is to compute the jacobian from the gradient.
Warning:
Do not call this function directly, call jacobian instead.
Parameters:
jacobian jacobian will be store in this argument
arg point where the jacobian will be computed
Reimplemented from roboptim::GenericDifferentiableFunction< T >.
template<typename T , typename FdgPolicy > std::ostream & roboptim::GenericFiniteDifferenceGradient< T, FdgPolicy >::print (std::ostream & o) const [virtual]
Display the function on the specified output stream.
Parameters:
o output stream used for display
Returns:
output stream
Reimplemented from roboptim::GenericDifferentiableFunction< T >.
References roboptim::decindent(), roboptim::iendl(), and roboptim::incindent().
template<typename T, typename FdgPolicy> roboptim::GenericFiniteDifferenceGradient< T, FdgPolicy >::ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericDifferentiableFunction< T >)
Member Data Documentation
template<typename T, typename FdgPolicy> const boost::shared_ptr<const GenericFunction<T> > roboptim::GenericFiniteDifferenceGradient< T, FdgPolicy >::adaptee_ [protected]
Shared pointer to the wrapped function.
template<typename T, typename FdgPolicy> const value_type roboptim::GenericFiniteDifferenceGradient< T, FdgPolicy >::epsilon_ [protected]
template<typename T, typename FdgPolicy> argument_t roboptim::GenericFiniteDifferenceGradient< T, FdgPolicy >::xEps_ [mutable, protected]