roboptim::GenericDifferentiableFunction< T > Class Template Reference
roboptim::GenericDifferentiableFunction< T > Class Template Reference
Mathematical abstract functions
Define an abstract derivable function (\(C^1\)).
#include <roboptim/core/differentiable-function.hh>
Public Types
typedef std::pair< size_type,
size_type > jacobianSize_t
Jacobian size type (pair of values).
Public Member Functions
ROBOPTIM_FUNCTION_FWD_TYPEDEFS_ (GenericFunction< T >)
ROBOPTIM_ADD_FLAG (ROBOPTIM_IS_DIFFERENTIABLE)
ROBOPTIM_GENERATE_TRAITS_REFS_ (gradient)
Gradient type.
ROBOPTIM_GENERATE_TRAITS_REFS_ (jacobian)
Jacobian type.
size_type gradientSize () const
Return the gradient size.
jacobianSize_t jacobianSize () const
Return the jacobian size as a pair.
bool isValidGradient (const_gradient_ref gradient) const
Check if the gradient is valid (check size).
bool isValidJacobian (const_jacobian_ref jacobian) const
Check if the jacobian is valid (check sizes).
jacobian_t jacobian (const_argument_ref argument) const
Computes the jacobian.
void jacobian (jacobian_ref jacobian, const_argument_ref argument) const
Computes the jacobian.
gradient_t gradient (const_argument_ref argument, size_type functionId=0) const
Computes the gradient.
void gradient (gradient_ref gradient, const_argument_ref argument, size_type functionId=0) const
Computes the gradient.
virtual std::ostream & print (std::ostream &o) const
Display the function on the specified output stream.
Protected Member Functions
GenericDifferentiableFunction (size_type inputSize, size_type outputSize=1, std::string name=std::string())
Concrete class constructor should call this constructor.
virtual void impl_jacobian (jacobian_ref jacobian, const_argument_ref arg) const
Jacobian evaluation.
virtual void impl_gradient (gradient_ref gradient, const_argument_ref argument, size_type functionId=0) const =0
Gradient evaluation.
template<>
void impl_jacobian (jacobian_ref jacobian, const_argument_ref argument) const
Detailed Description
template<typename T>
class roboptim::GenericDifferentiableFunction< T >
Define an abstract derivable function (\(C^1\)).
A derivable function which provides a way to compute its gradient/jacobian.
\[ f : x \rightarrow f(x) \]
\(x \in \mathbb{R}^n\), \(f(x) \in \mathbb{R}^m\) where \(n\) is the input size and \(m\) is the output size.
Gradient computation is done through the impl_gradient method that has to implemented by the concrete class inheriting this class.
Jacobian computation is automatically done by concatenating gradients together, however this naive implementation can be overridden by the concrete class.
The gradient of a \(\mathbb{R}^n \rightarrow \mathbb{R}^m\) function where \(n > 1\) and \(m > 1\) is a matrix. As this representation is costly, RobOptim considers these functions as \(m\) \(\mathbb{R}^n \rightarrow \mathbb{R}\) functions. Through that mechanism, gradients are always vectors and jacobian are always matrices. When the gradient or the jacobian has to be computed, one has to precise which of the \(m\) functions should be considered.
If \(m = 1\), then the function id must always be 0 and can be safely ignored in the gradient/jacobian computation. The class provides a default value for the function id so that these functions do not have to explicitly set the function id.
Examples:
problem-cc.cc.
Member Typedef Documentation
template<typename T> typedef std::pair<size_type, size_type> roboptim::GenericDifferentiableFunction< T >::jacobianSize_t
Jacobian size type (pair of values).
Constructor & Destructor Documentation
template<typename T > roboptim::GenericDifferentiableFunction< T >::GenericDifferentiableFunction (size_type inputSize, size_type outputSize = 1, std::string name = std::string ()) [protected]
Concrete class constructor should call this constructor.
Parameters:
inputSize input size (argument size)
outputSize output size (result size)
name function's name
Member Function Documentation
template<typename T> gradient_t roboptim::GenericDifferentiableFunction< T >::gradient (const_argument_ref argument, size_type functionId = 0) const [inline]
Computes the gradient.
Parameters:
argument point at which the gradient will be computed
functionId function id in split representation
Returns:
gradient vector
References roboptim::GenericDifferentiableFunction< T >::gradientSize(), and roboptim::GenericFunction< T >::outputSize().
Referenced by roboptim::checkGradient(), and roboptim::checkGradientAndThrow().
template<typename T> void roboptim::GenericDifferentiableFunction< T >::gradient (gradient_ref gradient, const_argument_ref argument, size_type functionId = 0) const [inline]
Computes the gradient.
Program will abort if the gradient size is wrong before or after the gradient computation.
Parameters:
gradient gradient will be stored in this argument
argument point at which the gradient will be computed
functionId function id in split representation
Returns:
gradient vector
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
References roboptim::GenericDifferentiableFunction< T >::impl_gradient(), roboptim::GenericFunction< T >::inputSize(), roboptim::is_malloc_allowed(), roboptim::GenericDifferentiableFunction< T >::isValidGradient(), roboptim::GenericFunction< T >::logger, roboptim::GenericFunction< T >::outputSize(), and roboptim::set_is_malloc_allowed().
template<typename T> size_type roboptim::GenericDifferentiableFunction< T >::gradientSize () const [inline]
Return the gradient size.
Gradient size is equals to the input size.
References roboptim::GenericFunction< T >::inputSize().
Referenced by roboptim::GenericDifferentiableFunction< T >::gradient(), and roboptim::GenericDifferentiableFunction< T >::isValidGradient().
template<typename T> virtual void roboptim::GenericDifferentiableFunction< T >::impl_gradient (gradient_ref gradient, const_argument_ref argument, size_type functionId = 0) const [protected, pure virtual]
Gradient evaluation.
Compute the gradient, has to be implemented in concrete classes. The gradient is computed for a specific sub-function which id is passed through the functionId argument.
Warning:
Do not call this function directly, call gradient instead.
Parameters:
gradient gradient will be store in this argument
argument point where the gradient will be computed
functionId evaluated function id in the split representation
Implemented in roboptim::GenericFiniteDifferenceGradient< T, FdgPolicy >, roboptim::NTimesDerivableFunction< 2 >, roboptim::GenericNumericQuadraticFunction< T >, roboptim::GenericNumericQuadraticFunction< T >, roboptim::GenericIdentityFunction< T >, roboptim::GenericNumericLinearFunction< T >, roboptim::GenericNumericLinearFunction< T >, roboptim::GenericConstantFunction< T >, roboptim::GenericIdentityFunction< T >, roboptim::Cos< T >, roboptim::Sin< T >, roboptim::GenericSumOfC1Squares< T >, roboptim::Cos< T >, roboptim::Polynomial< T >, and roboptim::Sin< T >.
Referenced by roboptim::GenericDifferentiableFunction< T >::gradient().
template<> void roboptim::GenericDifferentiableFunction< EigenMatrixSparse >::impl_jacobian (jacobian_ref jacobian, const_argument_ref argument) const [inline, protected]
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
Reimplemented in roboptim::GenericFiniteDifferenceGradient< T, FdgPolicy >, roboptim::GenericNumericQuadraticFunction< T >, roboptim::Cos< T >, roboptim::GenericConstantFunction< T >, roboptim::Sin< T >, roboptim::GenericNumericLinearFunction< T >, roboptim::GenericNumericQuadraticFunction< T >, roboptim::GenericIdentityFunction< T >, roboptim::Polynomial< T >, roboptim::Cos< T >, and roboptim::Sin< T >.
References roboptim::is_malloc_allowed(), and roboptim::set_is_malloc_allowed().
template<typename T > void roboptim::GenericDifferentiableFunction< T >::impl_jacobian (jacobian_ref jacobian, const_argument_ref arg) const [protected, virtual]
Jacobian evaluation.
Computes the jacobian, can be overridden by concrete classes. The default behavior is to compute the jacobian from the gradient.
Warning:
Do not call this function directly, call jacobian instead.
Parameters:
jacobian jacobian will be store in this argument
arg point where the jacobian will be computed
Reimplemented in roboptim::GenericFiniteDifferenceGradient< T, FdgPolicy >, roboptim::GenericNumericQuadraticFunction< T >, roboptim::Cos< T >, roboptim::GenericConstantFunction< T >, roboptim::Sin< T >, roboptim::GenericNumericLinearFunction< T >, roboptim::GenericNumericQuadraticFunction< T >, roboptim::GenericIdentityFunction< T >, roboptim::Polynomial< T >, roboptim::Cos< T >, and roboptim::Sin< T >.
Referenced by roboptim::GenericDifferentiableFunction< T >::jacobian().
template<typename T> bool roboptim::GenericDifferentiableFunction< T >::isValidGradient (const_gradient_ref gradient) const [inline]
Check if the gradient is valid (check size).
Parameters:
gradient checked gradient
Returns:
true if valid, false if not
References roboptim::GenericDifferentiableFunction< T >::gradientSize().
Referenced by roboptim::GenericDifferentiableFunction< T >::gradient().
template<typename T> bool roboptim::GenericDifferentiableFunction< T >::isValidJacobian (const_jacobian_ref jacobian) const [inline]
Check if the jacobian is valid (check sizes).
Parameters:
jacobian checked jacobian
Returns:
true if valid, false if not
References roboptim::GenericDifferentiableFunction< T >::jacobianSize().
Referenced by roboptim::GenericDifferentiableFunction< T >::jacobian().
template<typename T> jacobian_t roboptim::GenericDifferentiableFunction< T >::jacobian (const_argument_ref argument) const [inline]
Computes the jacobian.
Parameters:
argument point at which the jacobian will be computed
Returns:
jacobian matrix
References roboptim::GenericDifferentiableFunction< T >::jacobianSize().
Referenced by roboptim::checkJacobian(), roboptim::checkJacobianAndThrow(), roboptim::ScalingHelper< T >::computeScaling(), and roboptim::visualization::gnuplot::plot_jac().
template<typename T> void roboptim::GenericDifferentiableFunction< T >::jacobian (jacobian_ref jacobian, const_argument_ref argument) const [inline]
Computes the jacobian.
Program will abort if the jacobian size is wrong before or after the jacobian computation.
Parameters:
jacobian jacobian will be stored in this argument
argument point at which the jacobian will be computed
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
References roboptim::GenericDifferentiableFunction< T >::impl_jacobian(), roboptim::GenericFunction< T >::inputSize(), roboptim::is_malloc_allowed(), roboptim::GenericDifferentiableFunction< T >::isValidJacobian(), roboptim::GenericFunction< T >::logger, and roboptim::set_is_malloc_allowed().
template<typename T> jacobianSize_t roboptim::GenericDifferentiableFunction< T >::jacobianSize () const [inline]
Return the jacobian size as a pair.
Gradient size is equals to (output size, input size).
References roboptim::GenericFunction< T >::inputSize(), and roboptim::GenericFunction< T >::outputSize().
Referenced by roboptim::GenericDifferentiableFunction< T >::isValidJacobian(), and roboptim::GenericDifferentiableFunction< T >::jacobian().
template<typename T > std::ostream & roboptim::GenericDifferentiableFunction< T >::print (std::ostream & o) const [virtual]
Display the function on the specified output stream.
Parameters:
o output stream used for display
Returns:
output stream
Reimplemented from roboptim::GenericFunction< T >.
Reimplemented in roboptim::GenericFiniteDifferenceGradient< T, FdgPolicy >, roboptim::NTimesDerivableFunction< 2 >, roboptim::GenericTwiceDifferentiableFunction< T >, roboptim::GenericNumericQuadraticFunction< T >, roboptim::GenericConstantFunction< T >, roboptim::GenericNumericLinearFunction< T >, roboptim::Polynomial< T >, roboptim::GenericIdentityFunction< T >, roboptim::GenericLinearFunction< T >, roboptim::GenericQuadraticFunction< T >, roboptim::Cos< T >, and roboptim::Sin< T >.
References roboptim::indent().
template<typename T> roboptim::GenericDifferentiableFunction< T >::ROBOPTIM_ADD_FLAG (ROBOPTIM_IS_DIFFERENTIABLE)
template<typename T> roboptim::GenericDifferentiableFunction< T >::ROBOPTIM_FUNCTION_FWD_TYPEDEFS_ (GenericFunction< T >)
template<typename T> roboptim::GenericDifferentiableFunction< T >::ROBOPTIM_GENERATE_TRAITS_REFS_ (gradient)
Gradient type.
template<typename T> roboptim::GenericDifferentiableFunction< T >::ROBOPTIM_GENERATE_TRAITS_REFS_ (jacobian)
Jacobian type.