roboptim::GenericNumericLinearFunction< T > Class Template Reference
roboptim::GenericNumericLinearFunction< T > Class Template Reference
Mathematical functions
Build a linear function from a vector and a matrix.
#include <roboptim/core/numeric-linear-function.hh>
Public Member Functions
ROBOPTIM_TWICE_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericLinearFunction< T >)
ROBOPTIM_ADD_FLAG (ROBOPTIM_IS_NUMERIC_LINEAR)
GenericNumericLinearFunction (const_matrix_ref A, const_vector_ref b, std::string name=std::string())
Build a linear function from a matrix and a vector.
GenericNumericLinearFunction (const GenericLinearFunction< T > &)
Build a linear function from another one.
~GenericNumericLinearFunction ()
virtual std::ostream & print (std::ostream &) const
Display the function on the specified output stream.
const matrix_t & A () const
const vector_t & b () const
matrix_t & A ()
vector_t & b ()
void impl_compute (result_ref, const_argument_ref) const
Function evaluation.
void impl_gradient (gradient_ref, const_argument_ref, size_type=0) const
Gradient evaluation.
void impl_jacobian (jacobian_ref, const_argument_ref) const
Jacobian evaluation.
template<>
void impl_gradient (gradient_ref gradient, const_argument_ref, size_type idFunction) const
Gradient evaluation.
Detailed Description
template<typename T>
class roboptim::GenericNumericLinearFunction< T >
Build a linear function from a vector and a matrix.
Implement a linear function using the general formula:
\[f(x) = A x + b\]
where \(A\) and \(b\) are set when the class is instantiated.
Examples:
numeric-linear-function.cc.
Constructor & Destructor Documentation
template<typename T > roboptim::GenericNumericLinearFunction< T >::GenericNumericLinearFunction (const_matrix_ref A, const_vector_ref b, std::string name = std::string ())
Build a linear function from a matrix and a vector.
See class documentation for A and b definition.
Parameters:
A A matrix
b b vector
name function's name
References ROBOPTIM_ASSERT_MSG.
template<typename T > roboptim::GenericNumericLinearFunction< T >::GenericNumericLinearFunction (const GenericLinearFunction< T > & function)
Build a linear function from another one.
template<typename T > roboptim::GenericNumericLinearFunction< T >::~GenericNumericLinearFunction ()
Member Function Documentation
template<typename T> const matrix_t& roboptim::GenericNumericLinearFunction< T >::A () const [inline]
template<typename T> matrix_t& roboptim::GenericNumericLinearFunction< T >::A () [inline]
template<typename T> const vector_t& roboptim::GenericNumericLinearFunction< T >::b () const [inline]
template<typename T> vector_t& roboptim::GenericNumericLinearFunction< T >::b () [inline]
template<typename T > void roboptim::GenericNumericLinearFunction< T >::impl_compute (result_ref result, const_argument_ref argument) const [virtual]
Function evaluation.
Evaluate the function, has to be implemented in concrete classes.
Warning:
Do not call this function directly, call operator()(result_ref, const_argument_ref) const instead.
Parameters:
result result will be stored in this vector
argument point at which the function will be evaluated
Implements roboptim::GenericFunction< T >.
template<typename T > void roboptim::GenericNumericLinearFunction< T >::impl_gradient (gradient_ref gradient, const_argument_ref argument, size_type functionId = 0) const [virtual]
Gradient evaluation.
Compute the gradient, has to be implemented in concrete classes. The gradient is computed for a specific sub-function which id is passed through the functionId argument.
Warning:
Do not call this function directly, call gradient instead.
Parameters:
gradient gradient will be store in this argument
argument point where the gradient will be computed
functionId evaluated function id in the split representation
Implements roboptim::GenericDifferentiableFunction< T >.
template<> void roboptim::GenericNumericLinearFunction< EigenMatrixSparse >::impl_gradient (gradient_ref gradient, const_argument_ref argument, size_type functionId) const [inline, virtual]
Gradient evaluation.
Compute the gradient, has to be implemented in concrete classes. The gradient is computed for a specific sub-function which id is passed through the functionId argument.
Warning:
Do not call this function directly, call gradient instead.
Parameters:
gradient gradient will be store in this argument
argument point where the gradient will be computed
functionId evaluated function id in the split representation
Implements roboptim::GenericDifferentiableFunction< T >.
template<typename T > void roboptim::GenericNumericLinearFunction< T >::impl_jacobian (jacobian_ref jacobian, const_argument_ref arg) const [virtual]
Jacobian evaluation.
Computes the jacobian, can be overridden by concrete classes. The default behavior is to compute the jacobian from the gradient.
Warning:
Do not call this function directly, call jacobian instead.
Parameters:
jacobian jacobian will be store in this argument
arg point where the jacobian will be computed
Reimplemented from roboptim::GenericDifferentiableFunction< T >.
template<typename T > std::ostream & roboptim::GenericNumericLinearFunction< T >::print (std::ostream & o) const [virtual]
Display the function on the specified output stream.
Parameters:
o output stream used for display
Returns:
output stream
Reimplemented from roboptim::GenericLinearFunction< T >.
References roboptim::decindent(), roboptim::iendl(), roboptim::incindent(), and roboptim::toDense().
template<typename T> roboptim::GenericNumericLinearFunction< T >::ROBOPTIM_ADD_FLAG (ROBOPTIM_IS_NUMERIC_LINEAR)
template<typename T> roboptim::GenericNumericLinearFunction< T >::ROBOPTIM_TWICE_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericLinearFunction< T >)