roboptim::BadJacobian< T > Class Template Reference
roboptim::BadJacobian< T > Class Template Reference
Function decorators
Exception thrown when a Jacobian check fails.
#include <roboptim/core/decorator/finite-difference-gradient.hh>
Inherits std::runtime_error.
Public Member Functions
ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericDifferentiableFunction< T >)
BadJacobian (const_argument_ref x, const_jacobian_ref analyticalJacobian, const_jacobian_ref finiteDifferenceJacobian, const value_type &threshold)
Default constructor.
virtual ~BadJacobian () throw ()
virtual std::ostream & print (std::ostream &o) const
Display the exception on the specified output stream.
template<>
BadJacobian (const_argument_ref x, const_jacobian_ref analyticalJacobian, const_jacobian_ref finiteDifferenceJacobian, const value_type &threshold)
Public Attributes
argument_t x_
Jacobian has been computed for this point.
gradient_t analyticalJacobian_
Analytical Jacobian.
gradient_t finiteDifferenceJacobian_
Jacobian computed through finite differences.
value_type maxDelta_
Maximum error.
size_type maxDeltaRow_
Components containing the maximum error.
size_type maxDeltaCol_
value_type threshold_
Allowed threshold.
Detailed Description
template<typename T>
class roboptim::BadJacobian< T >
Exception thrown when a Jacobian check fails.
Constructor & Destructor Documentation
template<typename T > roboptim::BadJacobian< T >::BadJacobian (const_argument_ref x, const_jacobian_ref analyticalJacobian, const_jacobian_ref finiteDifferenceJacobian, const value_type & threshold)
Default constructor.
References roboptim::BadJacobian< T >::maxDelta_, roboptim::BadJacobian< T >::maxDeltaCol_, and roboptim::BadJacobian< T >::maxDeltaRow_.
template<typename T > roboptim::BadJacobian< T >::~BadJacobian () throw () [virtual]
template<> roboptim::BadJacobian< EigenMatrixSparse >::BadJacobian (const_argument_ref x, const_jacobian_ref analyticalJacobian, const_jacobian_ref finiteDifferenceJacobian, const value_type & threshold) [inline]
Member Function Documentation
template<typename T > std::ostream & roboptim::BadJacobian< T >::print (std::ostream & o) const [virtual]
Display the exception on the specified output stream.
Parameters:
o output stream used for display
Returns:
output stream
References roboptim::decindent(), roboptim::iendl(), roboptim::incindent(), and x_.
template<typename T> roboptim::BadJacobian< T >::ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericDifferentiableFunction< T >)
Member Data Documentation
template<typename T> gradient_t roboptim::BadJacobian< T >::analyticalJacobian_
Analytical Jacobian.
template<typename T> gradient_t roboptim::BadJacobian< T >::finiteDifferenceJacobian_
Jacobian computed through finite differences.
template<typename T> value_type roboptim::BadJacobian< T >::maxDelta_
Maximum error.
Referenced by roboptim::BadJacobian< T >::BadJacobian().
template<typename T> size_type roboptim::BadJacobian< T >::maxDeltaCol_
Referenced by roboptim::BadJacobian< T >::BadJacobian().
template<typename T> size_type roboptim::BadJacobian< T >::maxDeltaRow_
Components containing the maximum error.
Referenced by roboptim::BadJacobian< T >::BadJacobian().
template<typename T> value_type roboptim::BadJacobian< T >::threshold_
Allowed threshold.
template<typename T> argument_t roboptim::BadJacobian< T >::x_
Jacobian has been computed for this point.