roboptim::callback::Multiplexer< S > Class Template Reference
roboptim::callback::Multiplexer< S > Class Template Reference
Callback multiplexer.
#include <roboptim/core/callback/multiplexer.hh>
Public Types
typedef SolverCallback< S > parent_t
Parent type.
typedef S solver_t
Type of the solver.
typedef solver_t::problem_t problem_t
Type of the problem.
typedef SolverState< problem_t > solverState_t
Type of the state of the solver.
typedef SolverCallback< S > solverCallback_t
Solver callback type.
typedef boost::shared_ptr
< solverCallback_t > solverCallbackPtr_t
Pointer to a callback.
typedef std::vector
< solverCallbackPtr_t > solverCallbacks_t
Type of a vector of callbacks.
Public Types inherited from roboptim::SolverCallback< S >
typedef S solver_t
Solver type.
typedef solver_t::problem_t problem_t
Solver problem type.
typedef solver_t::callback_t callback_t
Per-iteration callback type.
typedef solver_t::solverState_t solverState_t
State of the solver.
Public Member Functions
Multiplexer (solver_t &solver)
Default constructor containing no callback.
Multiplexer (solver_t &solver, const solverCallbacks_t &callbacks)
Constructor filling the vector of callbacks.
virtual ~Multiplexer ()
Virtual destructor.
solverCallbacks_t & callbacks ()
Return the vector of callbacks.
const solverCallbacks_t & callbacks () const
Return the vector of callbacks.
virtual std::ostream & print (std::ostream &o) const
Display the callback on the specified output stream.
Public Member Functions inherited from roboptim::SolverCallback< S >
SolverCallback (const std::string &name="unnamed callback")
Solver callback constructor.
virtual ~SolverCallback ()
Destructor.
const std::string & name () const
Return the name of the callback.
callback_t callback ()
Callback function.
void operator() (const problem_t &pb, solverState_t &state)
Evaluate the callback.
Protected Member Functions
virtual void perIterationCallbackUnsafe (const problem_t &pb, solverState_t &state)
Meta-callback calling multiple callbacks.
void attach ()
Register the multiplexer with the solver.
void unregister ()
Unregister the multiplexer from the solver.
Protected Member Functions inherited from roboptim::SolverCallback< S >
virtual void perIterationCallback (const problem_t &pb, solverState_t &state)
Wrapper around the callback function that catch exceptions.
virtual void perIterationCallbackUnsafe (const problem_t &pb, solverState_t &state)=0
The actual callback function.
Detailed Description
template<typename S>
class roboptim::callback::Multiplexer< S >
Callback multiplexer.
This class turns multiple callback functions into one. Note that callbacks are processed in the order of the vector of functions provided. Beware of conflicts between multiple callbacks.
Template Parameters
S solver type.
Member Typedef Documentation
template<typename S > typedef SolverCallback<S> roboptim::callback::Multiplexer< S >::parent_t
Parent type.
template<typename S > typedef solver_t::problem_t roboptim::callback::Multiplexer< S >::problem_t
Type of the problem.
template<typename S > typedef S roboptim::callback::Multiplexer< S >::solver_t
Type of the solver.
template<typename S > typedef SolverCallback<S> roboptim::callback::Multiplexer< S >::solverCallback_t
Solver callback type.
template<typename S > typedef boost::shared_ptr<solverCallback_t> roboptim::callback::Multiplexer< S >::solverCallbackPtr_t
Pointer to a callback.
template<typename S > typedef std::vector<solverCallbackPtr_t> roboptim::callback::Multiplexer< S >::solverCallbacks_t
Type of a vector of callbacks.
template<typename S > typedef SolverState<problem_t> roboptim::callback::Multiplexer< S >::solverState_t
Type of the state of the solver.
Constructor & Destructor Documentation
template<typename S > roboptim::callback::Multiplexer< S >::Multiplexer (solver_t & solver) explicit
Default constructor containing no callback.
Parameters
solver solver the multiplexer will attach to.
References roboptim::callback::Multiplexer< S >::attach().
template<typename S > roboptim::callback::Multiplexer< S >::Multiplexer (solver_t & solver, const solverCallbacks_t & callbacks) explicit
Constructor filling the vector of callbacks.
Parameters
solver solver the multiplexer will attach to.
callbacks a vector of callbacks.
References roboptim::callback::Multiplexer< S >::attach().
template<typename S > roboptim::callback::Multiplexer< S >::~Multiplexer () virtual
Virtual destructor.
Member Function Documentation
template<typename S > void roboptim::callback::Multiplexer< S >::attach () protected
Register the multiplexer with the solver.
References roboptim::bind().
Referenced by roboptim::callback::Multiplexer< S >::Multiplexer().
template<typename S > Multiplexer< S >::solverCallbacks_t & roboptim::callback::Multiplexer< S >::callbacks ()
Return the vector of callbacks.
Returns
vector of callbacks.
template<typename S > const Multiplexer< S >::solverCallbacks_t & roboptim::callback::Multiplexer< S >::callbacks () const
Return the vector of callbacks.
Returns
vector of callbacks.
template<typename S > void roboptim::callback::Multiplexer< S >::perIterationCallbackUnsafe (const problem_t & pb, solverState_t & state) protected virtual
Meta-callback calling multiple callbacks.
Unsafe version that can throw exceptions.
Parameters
pb problem.
state solver state.
template<typename S > std::ostream & roboptim::callback::Multiplexer< S >::print (std::ostream & o) const virtual
Display the callback on the specified output stream.
Parameters
o output stream used for display.
Returns
output stream.
Reimplemented from roboptim::SolverCallback< S >.
References roboptim::decindent(), roboptim::iendl(), and roboptim::incindent().
template<typename S > void roboptim::callback::Multiplexer< S >::unregister () protected
Unregister the multiplexer from the solver.