roboptim::ResultAnalyzer< T >::LICQData Struct Reference
roboptim::ResultAnalyzer< T >::LICQData Struct Reference
Data for LICQ check.
#include <roboptim/core/result-analyzer.hh>
Public Member Functions
LICQData ()
bool isValid () const
Whether the input data is valid w.r.t. that query.
std::ostream & print (std::ostream &o) const
Print method.
Public Member Functions inherited from roboptim::ResultAnalyzer< T >::QueryData
bool operator_bool () const
Evaluate the query.
Public Attributes
size_type rank
size_type max_rank
Detailed Description
template<typename T>
struct roboptim::ResultAnalyzer< T >::LICQData
Data for LICQ check.
Constructor & Destructor Documentation
template<typename T> roboptim::ResultAnalyzer< T >::LICQData::LICQData ()
Member Function Documentation
template<typename T> bool roboptim::ResultAnalyzer< T >::LICQData::isValid () const virtual
Whether the input data is valid w.r.t. that query.
Implements roboptim::ResultAnalyzer< T >::QueryData.
template<typename T> std::ostream & roboptim::ResultAnalyzer< T >::LICQData::print (std::ostream & o) const virtual
Print method.
Implements roboptim::ResultAnalyzer< T >::QueryData.
References roboptim::fg::bold(), roboptim::decindent(), roboptim::fg::green(), roboptim::iendl(), roboptim::incindent(), roboptim::fg::red(), and roboptim::fg::reset().
Member Data Documentation
template<typename T> size_type roboptim::ResultAnalyzer< T >::LICQData::max_rank
Referenced by roboptim::ResultAnalyzer< T >::checkLICQ().
template<typename T> size_type roboptim::ResultAnalyzer< T >::LICQData::rank
Referenced by roboptim::ResultAnalyzer< T >::checkLICQ().