roboptim::GenericTwiceDifferentiableFunction< T > Class Template Reference
roboptim::GenericTwiceDifferentiableFunction< T > Class Template Reference abstract
Mathematical abstract functions
Define an abstract function which is twice-derivable (\(C^2\)).
#include <roboptim/core/twice-differentiable-function.hh>
Public Types
typedef std::pair< size_type,
size_type > hessianSize_t
Hessian size type represented as a pair of values.
Public Types inherited from roboptim::GenericDifferentiableFunction< T >
typedef std::pair< size_type,
size_type > jacobianSize_t
Jacobian size type (pair of values).
Public Types inherited from roboptim::GenericFunction< T >
typedef T traits_t
Traits type.
typedef GenericFunctionTraits
< T >::value_type value_type
Values type.
typedef GenericFunctionTraits
< T >::size_type size_type
Size type.
typedef std::string name_t
Type of a function argument name.
typedef std::vector< name_t > names_t
Type of a vector of function argument names.
typedef std::pair< value_type,
value_type > interval_t
Interval type (lower, upper).
typedef std::vector< interval_t > intervals_t
Vector of intervals.
typedef boost::tuple
< value_type, value_type,
value_type > discreteInterval_t
Types representing a discrete interval.
Public Member Functions
ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericDifferentiableFunction< T >)
ROBOPTIM_ADD_FLAG (ROBOPTIM_IS_TWICE_DIFFERENTIABLE)
ROBOPTIM_GENERATE_TRAITS_REFS_ (hessian)
Hessian type.
hessianSize_t hessianSize () const
Return the size of a hessian.
bool isValidHessian (const_hessian_ref hessian) const
Check if the hessian is valid (check sizes).
hessian_t hessian (const_argument_ref argument, size_type functionId=0) const
Compute the hessian at a given point.
void hessian (hessian_ref hessian, const_argument_ref argument, size_type functionId=0) const
Compute the hessian at a given point.
virtual std::ostream & print (std::ostream &) const
Display the function on the specified output stream.
Public Member Functions inherited from roboptim::GenericDifferentiableFunction< T >
ROBOPTIM_FUNCTION_FWD_TYPEDEFS_ (GenericFunction< T >)
ROBOPTIM_ADD_FLAG (ROBOPTIM_IS_DIFFERENTIABLE)
ROBOPTIM_GENERATE_TRAITS_REFS_ (gradient)
Gradient type.
ROBOPTIM_GENERATE_TRAITS_REFS_ (jacobian)
Jacobian type.
size_type gradientSize () const
Return the gradient size.
jacobianSize_t jacobianSize () const
Return the jacobian size as a pair.
bool isValidGradient (const_gradient_ref gradient) const
Check if the gradient is valid (check size).
bool isValidJacobian (const_jacobian_ref jacobian) const
Check if the jacobian is valid (check sizes).
jacobian_t jacobian (const_argument_ref argument) const
Computes the jacobian.
void jacobian (jacobian_ref jacobian, const_argument_ref argument) const
Computes the jacobian.
gradient_t gradient (const_argument_ref argument, size_type functionId=0) const
Computes the gradient.
void gradient (gradient_ref gradient, const_argument_ref argument, size_type functionId=0) const
Computes the gradient.
Public Member Functions inherited from roboptim::GenericFunction< T >
ROBOPTIM_DEFINE_FLAG_TYPE ()
ROBOPTIM_GENERATE_TRAITS_REFS_ (vector)
Basic (column) vector type.
ROBOPTIM_GENERATE_TRAITS_REFS_ (rowVector)
Row vector type.
ROBOPTIM_GENERATE_TRAITS_REFS_ (matrix)
Basic matrix type.
ROBOPTIM_GENERATE_TRAITS_REFS_ (result)
Type of a function evaluation result.
ROBOPTIM_GENERATE_TRAITS_REFS_ (argument)
Type of a function evaluation argument.
bool isValidResult (const_result_ref result) const
Check the given result size is valid.
GenericFunction< T >::size_type inputSize () const
Return the input size (i.e.
GenericFunction< T >::size_type outputSize () const
Return the output size (i.e.
virtual ~GenericFunction ()
Trivial destructor.
result_t operator() (const_argument_ref argument) const
Evaluate the function at a specified point.
void operator() (result_ref result, const_argument_ref argument) const
Evaluate the function at a specified point.
const std::string & getName () const
Get function name.
virtual flag_t getFlags () const
Get the type-checking flag.
template<class ExpectedType >
ExpectedType * castInto (bool check=false)
Cast function to ExpectedType.
template<class ExpectedType >
const ExpectedType * castInto (bool check=false) const
Cast function to ExpectedType (const).
template<class ExpectedType >
bool asType () const
Fonction type checking.
Protected Member Functions
GenericTwiceDifferentiableFunction (size_type inputSize, size_type outputSize=1, std::string name=std::string())
Concrete class constructor should call this constructor.
virtual void impl_hessian (hessian_ref hessian, const_argument_ref argument, size_type functionId=0) const =0
Hessian evaluation.
void setZero (hessian_ref symmetric) const
Set a symmetric matrix to zero.
Protected Member Functions inherited from roboptim::GenericDifferentiableFunction< T >
GenericDifferentiableFunction (size_type inputSize, size_type outputSize=1, std::string name=std::string())
Concrete class constructor should call this constructor.
virtual void impl_jacobian (jacobian_ref jacobian, const_argument_ref arg) const
Jacobian evaluation.
virtual void impl_gradient (gradient_ref gradient, const_argument_ref argument, size_type functionId=0) const =0
Gradient evaluation.
template<>
void impl_jacobian (jacobian_ref jacobian, const_argument_ref argument) const
Protected Member Functions inherited from roboptim::GenericFunction< T >
GenericFunction (size_type inputSize, size_type outputSize=1, std::string name=std::string())
Concrete class constructor should call this constructor.
virtual void impl_compute (result_ref result, const_argument_ref argument) const =0
Function evaluation.
Additional Inherited Members
Static Public Member Functions inherited from roboptim::GenericFunction< T >
static value_type epsilon ()
Get the value of the machine epsilon, useful for floating types comparison.
static value_type infinity ()
Get the value that symbolizes positive infinity.
static interval_t makeInterval (value_type l, value_type u)
Construct an interval from a lower and upper bound.
static interval_t makeInfiniteInterval ()
Construct an infinite interval.
static interval_t makeLowerInterval (value_type l)
Construct an interval from a lower bound.
static interval_t makeUpperInterval (value_type u)
Construct an interval from an upper bound.
static value_type getLowerBound (const interval_t &interval)
Get the lower bound of an interval.
static value_type getUpperBound (const interval_t &interval)
Get the upper bound of an interval.
static discreteInterval_t makeDiscreteInterval (value_type min, value_type max, value_type step)
Construct a discrete interval.
static discreteInterval_t makeDiscreteInterval (interval_t interval, value_type step)
Construct a discrete interval.
static value_type getLowerBound (const discreteInterval_t &interval)
Get the lower bound of a discrete interval.
static value_type getUpperBound (const discreteInterval_t &interval)
Get the upper bound of a discrete interval.
static value_type getStep (const discreteInterval_t &interval)
Get the upper step of a discrete interval.
template<typename F >
static void foreach (const discreteInterval_t interval, F functor)
Iterate on an interval.
template<typename F >
static void foreach (const interval_t interval, const size_type n, F functor)
Iterate on an interval.
Static Public Attributes inherited from roboptim::GenericFunction< T >
static const flag_t flags = ROBOPTIM_IS_FUNCTION
Flag representing the Roboptim Function type.
Detailed Description
template<typename T>
class roboptim::GenericTwiceDifferentiableFunction< T >
Define an abstract function which is twice-derivable (\(C^2\)).
A twice-derivable function is a derivable function which provides a way to compute its hessian.
\[ f : x \rightarrow f(x) \]
\(x \in \mathbb{R}^n\), \(f(x) \in \mathbb{R}^m\) where \(n\) is the input size and \(m\) is the output size.
Hessian computation is done through the impl_hessian method that has to implemented by the concrete class inheriting this class.
The hessian of a \(\mathbb{R}^n \rightarrow \mathbb{R}^m\) function where \(n > 1\) and \(m > 1\) is a tensor. To avoid this costly representation, the function is split into \(m\) \(\mathbb{R}^n \rightarrow \mathbb{R}\) functions. See DifferentiableFunction documentation for more information.
Member Typedef Documentation
template<typename T > typedef std::pair<size_type, size_type> roboptim::GenericTwiceDifferentiableFunction< T >::hessianSize_t
Hessian size type represented as a pair of values.
Constructor & Destructor Documentation
template<typename T > roboptim::GenericTwiceDifferentiableFunction< T >::GenericTwiceDifferentiableFunction (size_type inputSize, size_type outputSize = 1, std::string name = std::string ()) protected
Concrete class constructor should call this constructor.
Parameters
inputSize input size (argument size)
outputSize output size (result size)
name function's name
Exceptions
std::runtime_error
Member Function Documentation
template<typename T > hessian_t roboptim::GenericTwiceDifferentiableFunction< T >::hessian (const_argument_ref argument, size_type functionId = 0) const inline
Compute the hessian at a given point.
Program will abort if the argument size is wrong.
Parameters
argument point where the hessian will be computed
functionId evaluated function id in the split representation
Returns
computed hessian
References roboptim::GenericTwiceDifferentiableFunction< T >::hessianSize(), and roboptim::GenericTwiceDifferentiableFunction< T >::setZero().
template<typename T > void roboptim::GenericTwiceDifferentiableFunction< T >::hessian (hessian_ref hessian, const_argument_ref argument, size_type functionId = 0) const inline
Compute the hessian at a given point.
Program will abort if the argument size is wrong.
Parameters
hessian hessian will be stored here
argument point where the hessian will be computed
functionId evaluated function id in the split representation
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
References roboptim::GenericTwiceDifferentiableFunction< T >::impl_hessian(), roboptim::is_malloc_allowed(), roboptim::GenericTwiceDifferentiableFunction< T >::isValidHessian(), and roboptim::set_is_malloc_allowed().
template<typename T > hessianSize_t roboptim::GenericTwiceDifferentiableFunction< T >::hessianSize () const inline
Return the size of a hessian.
Hessian size is equal to (input size, input size).
Returns
hessian's size as a pair
References roboptim::GenericFunction< T >::inputSize().
Referenced by roboptim::GenericTwiceDifferentiableFunction< T >::hessian(), and roboptim::GenericTwiceDifferentiableFunction< T >::isValidHessian().
template<typename T > virtual void roboptim::GenericTwiceDifferentiableFunction< T >::impl_hessian (hessian_ref hessian, const_argument_ref argument, size_type functionId = 0) const protected pure virtual
Hessian evaluation.
Compute the hessian, has to be implemented in concrete classes. The hessian is computed for a specific sub-function which id is passed through the functionId argument.
Warning
Do not call this function directly, call hessian instead.
Parameters
hessian hessian will be stored here
argument point where the hessian will be computed
functionId evaluated function id in the split representation
Implemented in roboptim::NTimesDerivableFunction< 2 >, roboptim::GenericNumericQuadraticFunction< T >, roboptim::Cos< T >, roboptim::Sin< T >, roboptim::Polynomial< T >, roboptim::Cos< T >, roboptim::Sin< T >, and roboptim::GenericLinearFunction< T >.
Referenced by roboptim::GenericTwiceDifferentiableFunction< T >::hessian().
template<typename T > bool roboptim::GenericTwiceDifferentiableFunction< T >::isValidHessian (const_hessian_ref hessian) const inline
Check if the hessian is valid (check sizes).
Parameters
hessian hessian that will be checked
Returns
true if valid, false if not
References roboptim::GenericTwiceDifferentiableFunction< T >::hessianSize().
Referenced by roboptim::GenericTwiceDifferentiableFunction< T >::hessian().
template<typename T > std::ostream & roboptim::GenericTwiceDifferentiableFunction< T >::print (std::ostream & o) const virtual
Display the function on the specified output stream.
Parameters
o output stream used for display
Returns
output stream
Reimplemented from roboptim::GenericDifferentiableFunction< T >.
Reimplemented in roboptim::NTimesDerivableFunction< 2 >, roboptim::GenericNumericQuadraticFunction< T >, roboptim::GenericConstantFunction< T >, roboptim::GenericNumericLinearFunction< T >, roboptim::Polynomial< T >, roboptim::GenericIdentityFunction< T >, roboptim::GenericLinearFunction< T >, roboptim::GenericQuadraticFunction< T >, roboptim::Cos< T >, and roboptim::Sin< T >.
References roboptim::indent().
template<typename T > roboptim::GenericTwiceDifferentiableFunction< T >::ROBOPTIM_ADD_FLAG (ROBOPTIM_IS_TWICE_DIFFERENTIABLE)
template<typename T > roboptim::GenericTwiceDifferentiableFunction< T >::ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericDifferentiableFunction< T >)
template<typename T > roboptim::GenericTwiceDifferentiableFunction< T >::ROBOPTIM_GENERATE_TRAITS_REFS_ (hessian)
Hessian type.
Hessians are symmetric matrices.
template<typename T > void roboptim::GenericTwiceDifferentiableFunction< T >::setZero (hessian_ref symmetric) const inline protected
Set a symmetric matrix to zero.
Note
there might be an eigen function to do that.
Referenced by roboptim::GenericTwiceDifferentiableFunction< T >::hessian().