roboptim::NTimesDerivableFunction< 2 > Class Template Reference
roboptim::NTimesDerivableFunction< 2 > Class Template Reference abstract
Mathematical functions
Explicit specialization for the stop case of NTimesDerivable class.
#include <roboptim/core/n-times-derivable-function.hh>
Public Types
typedef TwiceDifferentiableFunction parent_t
Parent type.
typedef parent_t::traits_t traits_t
Traits type.
Public Types inherited from roboptim::GenericTwiceDifferentiableFunction< T >
typedef std::pair< size_type,
size_type > hessianSize_t
Hessian size type represented as a pair of values.
Public Types inherited from roboptim::GenericDifferentiableFunction< T >
typedef std::pair< size_type,
size_type > jacobianSize_t
Jacobian size type (pair of values).
Public Types inherited from roboptim::GenericFunction< T >
typedef T traits_t
Traits type.
typedef GenericFunctionTraits
< T >::value_type value_type
Values type.
typedef GenericFunctionTraits
< T >::size_type size_type
Size type.
typedef std::string name_t
Type of a function argument name.
typedef std::vector< name_t > names_t
Type of a vector of function argument names.
typedef std::pair< value_type,
value_type > interval_t
Interval type (lower, upper).
typedef std::vector< interval_t > intervals_t
Vector of intervals.
typedef boost::tuple
< value_type, value_type,
value_type > discreteInterval_t
Types representing a discrete interval.
Public Member Functions
ROBOPTIM_GENERATE_TRAITS_REFS_T (derivative, traits_t)
Derivative type.
virtual size_type derivabilityOrderMax () const
Returns the maximum derivability order (relevant for N>2 only)
virtual ~NTimesDerivableFunction ()
size_type derivativeSize () const
Return the size of the derivative vector.
bool isValidDerivative (const_derivative_ref derivative) const
Check if a derivative is valid (check sizes).
result_t operator() (value_type argument) const
Evaluate the function at a specified point.
void operator() (result_ref result, value_type argument) const
Evaluate the function at a specified point.
derivative_t derivative (value_type argument, size_type order=1) const
Compute the derivative of the function.
void derivative (derivative_ref derivative, value_type argument, size_type order=1) const
Compute the derivative of the function.
virtual std::ostream & print (std::ostream &o) const
Display the function on the specified output stream.
Public Member Functions inherited from roboptim::GenericTwiceDifferentiableFunction< T >
ROBOPTIM_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericDifferentiableFunction< T >)
ROBOPTIM_ADD_FLAG (ROBOPTIM_IS_TWICE_DIFFERENTIABLE)
ROBOPTIM_GENERATE_TRAITS_REFS_ (hessian)
Hessian type.
hessianSize_t hessianSize () const
Return the size of a hessian.
bool isValidHessian (const_hessian_ref hessian) const
Check if the hessian is valid (check sizes).
hessian_t hessian (const_argument_ref argument, size_type functionId=0) const
Compute the hessian at a given point.
void hessian (hessian_ref hessian, const_argument_ref argument, size_type functionId=0) const
Compute the hessian at a given point.
Public Member Functions inherited from roboptim::GenericDifferentiableFunction< T >
ROBOPTIM_FUNCTION_FWD_TYPEDEFS_ (GenericFunction< T >)
ROBOPTIM_ADD_FLAG (ROBOPTIM_IS_DIFFERENTIABLE)
ROBOPTIM_GENERATE_TRAITS_REFS_ (gradient)
Gradient type.
ROBOPTIM_GENERATE_TRAITS_REFS_ (jacobian)
Jacobian type.
size_type gradientSize () const
Return the gradient size.
jacobianSize_t jacobianSize () const
Return the jacobian size as a pair.
bool isValidGradient (const_gradient_ref gradient) const
Check if the gradient is valid (check size).
bool isValidJacobian (const_jacobian_ref jacobian) const
Check if the jacobian is valid (check sizes).
jacobian_t jacobian (const_argument_ref argument) const
Computes the jacobian.
void jacobian (jacobian_ref jacobian, const_argument_ref argument) const
Computes the jacobian.
gradient_t gradient (const_argument_ref argument, size_type functionId=0) const
Computes the gradient.
void gradient (gradient_ref gradient, const_argument_ref argument, size_type functionId=0) const
Computes the gradient.
Public Member Functions inherited from roboptim::GenericFunction< T >
ROBOPTIM_DEFINE_FLAG_TYPE ()
ROBOPTIM_GENERATE_TRAITS_REFS_ (vector)
Basic (column) vector type.
ROBOPTIM_GENERATE_TRAITS_REFS_ (rowVector)
Row vector type.
ROBOPTIM_GENERATE_TRAITS_REFS_ (matrix)
Basic matrix type.
ROBOPTIM_GENERATE_TRAITS_REFS_ (result)
Type of a function evaluation result.
ROBOPTIM_GENERATE_TRAITS_REFS_ (argument)
Type of a function evaluation argument.
bool isValidResult (const_result_ref result) const
Check the given result size is valid.
GenericFunction< T >::size_type inputSize () const
Return the input size (i.e.
GenericFunction< T >::size_type outputSize () const
Return the output size (i.e.
virtual ~GenericFunction ()
Trivial destructor.
result_t operator() (const_argument_ref argument) const
Evaluate the function at a specified point.
void operator() (result_ref result, const_argument_ref argument) const
Evaluate the function at a specified point.
const std::string & getName () const
Get function name.
virtual flag_t getFlags () const
Get the type-checking flag.
template<class ExpectedType >
ExpectedType * castInto (bool check=false)
Cast function to ExpectedType.
template<class ExpectedType >
const ExpectedType * castInto (bool check=false) const
Cast function to ExpectedType (const).
template<class ExpectedType >
bool asType () const
Fonction type checking.
Static Public Attributes
static const size_type derivabilityOrder = 2
Function derivability order.
Static Public Attributes inherited from roboptim::GenericFunction< T >
static const flag_t flags = ROBOPTIM_IS_FUNCTION
Flag representing the Roboptim Function type.
Protected Member Functions
NTimesDerivableFunction (size_type outputSize=1, std::string name=std::string())
Concrete class constructor should call this constructor.
void impl_compute (result_ref result, const_argument_ref argument) const
Function evaluation.
virtual void impl_compute (result_ref result, value_type t) const =0
Function evaluation.
void impl_gradient (gradient_ref gradient, const_argument_ref argument, size_type functionId=0) const
Gradient evaluation.
virtual void impl_derivative (derivative_ref derivative, value_type argument, size_type order=1) const =0
Derivative evaluation.
void impl_hessian (hessian_ref hessian, const_argument_ref argument, size_type functionId=0) const
Hessian evaluation.
Protected Member Functions inherited from roboptim::GenericTwiceDifferentiableFunction< T >
GenericTwiceDifferentiableFunction (size_type inputSize, size_type outputSize=1, std::string name=std::string())
Concrete class constructor should call this constructor.
void setZero (hessian_ref symmetric) const
Set a symmetric matrix to zero.
Protected Member Functions inherited from roboptim::GenericDifferentiableFunction< T >
GenericDifferentiableFunction (size_type inputSize, size_type outputSize=1, std::string name=std::string())
Concrete class constructor should call this constructor.
virtual void impl_jacobian (jacobian_ref jacobian, const_argument_ref arg) const
Jacobian evaluation.
template<>
void impl_jacobian (jacobian_ref jacobian, const_argument_ref argument) const
Protected Member Functions inherited from roboptim::GenericFunction< T >
GenericFunction (size_type inputSize, size_type outputSize=1, std::string name=std::string())
Concrete class constructor should call this constructor.
Additional Inherited Members
Static Public Member Functions inherited from roboptim::GenericFunction< T >
static value_type epsilon ()
Get the value of the machine epsilon, useful for floating types comparison.
static value_type infinity ()
Get the value that symbolizes positive infinity.
static interval_t makeInterval (value_type l, value_type u)
Construct an interval from a lower and upper bound.
static interval_t makeInfiniteInterval ()
Construct an infinite interval.
static interval_t makeLowerInterval (value_type l)
Construct an interval from a lower bound.
static interval_t makeUpperInterval (value_type u)
Construct an interval from an upper bound.
static value_type getLowerBound (const interval_t &interval)
Get the lower bound of an interval.
static value_type getUpperBound (const interval_t &interval)
Get the upper bound of an interval.
static discreteInterval_t makeDiscreteInterval (value_type min, value_type max, value_type step)
Construct a discrete interval.
static discreteInterval_t makeDiscreteInterval (interval_t interval, value_type step)
Construct a discrete interval.
static value_type getLowerBound (const discreteInterval_t &interval)
Get the lower bound of a discrete interval.
static value_type getUpperBound (const discreteInterval_t &interval)
Get the upper bound of a discrete interval.
static value_type getStep (const discreteInterval_t &interval)
Get the upper step of a discrete interval.
template<typename F >
static void foreach (const discreteInterval_t interval, F functor)
Iterate on an interval.
template<typename F >
static void foreach (const interval_t interval, const size_type n, F functor)
Iterate on an interval.
Static Protected Attributes inherited from roboptim::GenericFunction< T >
static log4cxx::LoggerPtr logger
Pointer to function logger (see log4cxx documentation).
Detailed Description
template<>
class roboptim::NTimesDerivableFunction< 2 >
Explicit specialization for the stop case of NTimesDerivable class.
This specialization defines the interface of a ``n times derivable function'' and implements generic methods required by upper classes using this class specific interface.
Member Typedef Documentation
typedef TwiceDifferentiableFunction roboptim::NTimesDerivableFunction< 2 >::parent_t
Parent type.
typedef parent_t::traits_t roboptim::NTimesDerivableFunction< 2 >::traits_t
Traits type.
Constructor & Destructor Documentation
virtual roboptim::NTimesDerivableFunction< 2 >::~NTimesDerivableFunction () inline virtual
roboptim::NTimesDerivableFunction< 2 >::NTimesDerivableFunction (size_type outputSize = 1, std::string name = std::string ()) inline protected
Concrete class constructor should call this constructor.
Parameters
outputSize output size (result size)
name function's name
Member Function Documentation
virtual size_type roboptim::NTimesDerivableFunction< 2 >::derivabilityOrderMax () const inline virtual
Returns the maximum derivability order (relevant for N>2 only)
derivative_t roboptim::NTimesDerivableFunction< 2 >::derivative (value_type argument, size_type order = 1) const inline
Compute the derivative of the function.
Derivative is computed for a certain order, at a given point.
Parameters
argument point at which the derivative will be computed
order derivative order (if 0 then function is evaluated)
Returns
derivative vector
References roboptim::derivative().
void roboptim::NTimesDerivableFunction< 2 >::derivative (derivative_ref derivative, value_type argument, size_type order = 1) const inline
Compute the derivative of the function.
Derivative is computed for a certain order, at a given point.
Parameters
derivative derivative will be stored in this vector
argument point at which the derivative will be computed
order derivative order (if 0 then function is evaluated)
References roboptim::NTimesDerivableFunction< DerivabilityOrder >::derivabilityOrderMax().
size_type roboptim::NTimesDerivableFunction< 2 >::derivativeSize () const inline
Return the size of the derivative vector.
Returns
derivative vector size
void roboptim::NTimesDerivableFunction< 2 >::impl_compute (result_ref result, const_argument_ref argument) const inline protected virtual
Function evaluation.
Implement generic function evaluation, as required by Function, using this class evaluation method (using a double instead of a vector).
Warning
Do not call this function directly, call #operator()(result_ref, const_argument_ref) const instead.
Parameters
result result will be stored in this vector
argument point at which the function will be evaluated
Implements roboptim::GenericFunction< T >.
virtual void roboptim::NTimesDerivableFunction< 2 >::impl_compute (result_ref result, value_type t) const protected pure virtual
Function evaluation.
Evaluate the function, has to be implemented in concrete classes.
Warning
Do not call this function directly, call #operator()(double) const instead.
Parameters
result result will be stored in this vector
t point at which the function will be evaluated
virtual void roboptim::NTimesDerivableFunction< 2 >::impl_derivative (derivative_ref derivative, value_type argument, size_type order = 1) const protected pure virtual
Derivative evaluation.
Compute the derivative, has to be implemented in concrete classes.
Warning
Do not call this function directly, call derivative instead.
Parameters
derivative derivative will be store in this argument
argument point where the gradient will be computed
order derivative order (if 0 evaluates the function)
void roboptim::NTimesDerivableFunction< 2 >::impl_gradient (gradient_ref gradient, const_argument_ref argument, size_type functionId = 0) const inline protected virtual
Gradient evaluation.
Implement the gradient computation, as required by DerivableFunction. The gradient is computed for a specific sub-function which id is passed through the functionId argument.
Warning
Do not call this function directly, call gradient or derivative instead.
Parameters
gradient gradient will be store in this argument
argument point where the gradient will be computed
functionId evaluated function id in the split representation
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
Implements roboptim::GenericDifferentiableFunction< T >.
References roboptim::derivative(), roboptim::is_malloc_allowed(), and roboptim::set_is_malloc_allowed().
void roboptim::NTimesDerivableFunction< 2 >::impl_hessian (hessian_ref hessian, const_argument_ref argument, size_type functionId = 0) const inline protected virtual
Hessian evaluation.
Implement the hessian computation, as required by the TwiceDerivableFunction class using the derivative method. The hessian is computed for a specific sub-function which id is passed through the functionId argument.
Warning
Do not call this function directly, call hessian instead.
Parameters
hessian hessian will be stored here
argument point where the hessian will be computed
functionId evaluated function id in the split representation
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
ROBOPTIM_DO_NOT_CHECK_ALLOCATION
Implements roboptim::GenericTwiceDifferentiableFunction< T >.
References roboptim::derivative(), roboptim::is_malloc_allowed(), and roboptim::set_is_malloc_allowed().
bool roboptim::NTimesDerivableFunction< 2 >::isValidDerivative (const_derivative_ref derivative) const inline
Check if a derivative is valid (check sizes).
Parameters
derivative derivative vector to be checked
Returns
true if valid, false if not
result_t roboptim::NTimesDerivableFunction< 2 >::operator() (value_type argument) const inline
Evaluate the function at a specified point.
The program will abort if the argument does not have the expected size.
Parameters
argument point at which the function will be evaluated
Returns
computed result
void roboptim::NTimesDerivableFunction< 2 >::operator() (result_ref result, value_type argument) const inline
Evaluate the function at a specified point.
The program will abort if the argument does not have the expected size.
Parameters
result result will be stored in this vector
argument point at which the function will be evaluated
Returns
computed result
virtual std::ostream& roboptim::NTimesDerivableFunction< 2 >::print (std::ostream & o) const inline virtual
Display the function on the specified output stream.
Parameters
o output stream used for display
Returns
output stream
Reimplemented from roboptim::GenericTwiceDifferentiableFunction< T >.
References roboptim::NTimesDerivableFunction< DerivabilityOrder >::derivabilityOrderMax().
roboptim::NTimesDerivableFunction< 2 >::ROBOPTIM_GENERATE_TRAITS_REFS_T (derivative , traits_t)
Derivative type.
Derivatives are column vectors.
Member Data Documentation
const size_type roboptim::NTimesDerivableFunction< 2 >::derivabilityOrder = 2 static
Function derivability order.
One static const variable per class in inheritance structure.