roboptim::ResultAnalyzer< T >::KKTData Struct Reference
roboptim::ResultAnalyzer< T >::KKTData Struct Reference
Data for KKT check.
#include <roboptim/core/result-analyzer.hh>
Public Member Functions
KKTData ()
bool isValid () const
Whether the input data is valid w.r.t. that query.
std::ostream & print (std::ostream &o) const
Print method.
Public Member Functions inherited from roboptim::ResultAnalyzer< T >::QueryData
bool operator_bool () const
Evaluate the query.
Public Attributes
gradient_t grad_L
vector_t lambda
Lagrange multipliers λ.
value_type violation
Constraint violation.
value_type complementary_slackness
Complementary slackness.
bool dual_feasible
Whether dual feasibility is satisfied.
value_type eps
Detailed Description
template<typename T>
struct roboptim::ResultAnalyzer< T >::KKTData
Data for KKT check.
Constructor & Destructor Documentation
template<typename T> roboptim::ResultAnalyzer< T >::KKTData::KKTData ()
Member Function Documentation
template<typename T> bool roboptim::ResultAnalyzer< T >::KKTData::isValid () const virtual
Whether the input data is valid w.r.t. that query.
Implements roboptim::ResultAnalyzer< T >::QueryData.
template<typename T> std::ostream & roboptim::ResultAnalyzer< T >::KKTData::print (std::ostream & o) const virtual
Print method.
Implements roboptim::ResultAnalyzer< T >::QueryData.
References roboptim::fg::bold(), roboptim::decindent(), roboptim::fg::green(), roboptim::iendl(), roboptim::incindent(), roboptim::fg::red(), roboptim::fg::reset(), and roboptim::toDense().
Member Data Documentation
template<typename T> value_type roboptim::ResultAnalyzer< T >::KKTData::complementary_slackness
Complementary slackness.
Referenced by roboptim::ResultAnalyzer< T >::checkKKT().
template<typename T> bool roboptim::ResultAnalyzer< T >::KKTData::dual_feasible
Whether dual feasibility is satisfied.
Referenced by roboptim::ResultAnalyzer< T >::checkKKT().
template<typename T> value_type roboptim::ResultAnalyzer< T >::KKTData::eps
Referenced by roboptim::ResultAnalyzer< T >::checkKKT().
template<typename T> gradient_t roboptim::ResultAnalyzer< T >::KKTData::grad_L
Referenced by roboptim::ResultAnalyzer< T >::checkKKT().
template<typename T> vector_t roboptim::ResultAnalyzer< T >::KKTData::lambda
Lagrange multipliers λ.
Referenced by roboptim::ResultAnalyzer< T >::checkKKT().
template<typename T> value_type roboptim::ResultAnalyzer< T >::KKTData::violation
Constraint violation.
Referenced by roboptim::ResultAnalyzer< T >::checkKKT().