roboptim::ResultAnalyzer< T >::NullGradientData Struct Reference
roboptim::ResultAnalyzer< T >::NullGradientData Struct Reference
Data for null-gradient check.
#include <roboptim/core/result-analyzer.hh>
Public Types
typedef problem_t::constraint_t constraint_t
Public Member Functions
NullGradientData ()
bool isValid () const
Whether the input data is valid w.r.t. that query.
std::ostream & print (std::ostream &o) const
Print method.
Public Member Functions inherited from roboptim::ResultAnalyzer< T >::QueryData
bool operator_bool () const
Evaluate the query.
Public Attributes
size_type null_rows
std::map< const constraint_t,
std::vector< size_type > > constraint_indices
Detailed Description
template<typename T>
struct roboptim::ResultAnalyzer< T >::NullGradientData
Data for null-gradient check.
Member Typedef Documentation
template<typename T> typedef problem_t::constraint_t roboptim::ResultAnalyzer< T >::NullGradientData::constraint_t
Constructor & Destructor Documentation
template<typename T> roboptim::ResultAnalyzer< T >::NullGradientData::NullGradientData ()
Member Function Documentation
template<typename T> bool roboptim::ResultAnalyzer< T >::NullGradientData::isValid () const virtual
Whether the input data is valid w.r.t. that query.
Implements roboptim::ResultAnalyzer< T >::QueryData.
template<typename T> std::ostream & roboptim::ResultAnalyzer< T >::NullGradientData::print (std::ostream & o) const virtual
Print method.
Implements roboptim::ResultAnalyzer< T >::QueryData.
References roboptim::fg::bold(), roboptim::decindent(), roboptim::fg::green(), roboptim::iendl(), roboptim::incindent(), roboptim::map(), roboptim::fg::red(), and roboptim::fg::reset().
Member Data Documentation
template<typename T> std::map<const constraint_t, std::vector<size_type> > roboptim::ResultAnalyzer< T >::NullGradientData::constraint_indices
Referenced by roboptim::ResultAnalyzer< T >::checkNullGradient().
template<typename T> size_type roboptim::ResultAnalyzer< T >::NullGradientData::null_rows
Referenced by roboptim::ResultAnalyzer< T >::checkNullGradient().