roboptim::fg Namespace Reference
roboptim::fg Namespace Reference
Functions
bool isTtyStream (const std::ostream &o)
std::ostream & reset (std::ostream &o)
Reset everything (color, attributes).
std::ostream & red (std::ostream &o)
std::ostream & green (std::ostream &o)
std::ostream & yellow (std::ostream &o)
std::ostream & blue (std::ostream &o)
std::ostream & orange (std::ostream &o)
std::ostream & resetfg (std::ostream &o)
Default foreground color.
std::ostream & bold (std::ostream &o)
std::ostream & italic (std::ostream &o)
std::ostream & normal (std::ostream &o)
Reset attributes (bold, italic...).
std::ostream & ok (std::ostream &o)
std::ostream & fail (std::ostream &o)
std::ostream & warn (std::ostream &o)
Function Documentation
std::ostream& roboptim::fg::blue (std::ostream & o) [inline]
References ROBOPTIM_CORE_FILTER_TTY.
std::ostream& roboptim::fg::bold (std::ostream & o) [inline]
References ROBOPTIM_CORE_FILTER_TTY.
Referenced by roboptim::assertion_failed(), and roboptim::assertion_failed_msg().
std::ostream& roboptim::fg::fail (std::ostream & o) [inline]
References red().
Referenced by roboptim::assertion_failed(), roboptim::assertion_failed_msg(), roboptim::detail::printConstraint< P >::operator()(), roboptim::SolverError::print(), and roboptim::Problem< T >::print().
std::ostream& roboptim::fg::green (std::ostream & o) [inline]
References ROBOPTIM_CORE_FILTER_TTY.
Referenced by ok().
bool roboptim::fg::isTtyStream (const std::ostream & o) [inline]
std::ostream& roboptim::fg::italic (std::ostream & o) [inline]
References ROBOPTIM_CORE_FILTER_TTY.
std::ostream& roboptim::fg::normal (std::ostream & o) [inline]
Reset attributes (bold, italic...).
References ROBOPTIM_CORE_FILTER_TTY.
std::ostream& roboptim::fg::ok (std::ostream & o) [inline]
References green().
Referenced by roboptim::detail::printConstraint< P >::operator()(), and roboptim::Problem< T >::print().
std::ostream& roboptim::fg::orange (std::ostream & o) [inline]
References ROBOPTIM_CORE_FILTER_TTY.
Referenced by warn().
std::ostream& roboptim::fg::red (std::ostream & o) [inline]
References ROBOPTIM_CORE_FILTER_TTY.
Referenced by fail().
std::ostream& roboptim::fg::reset (std::ostream & o) [inline]
Reset everything (color, attributes).
Examples:
visualization-gnuplot-simple.cc.
References ROBOPTIM_CORE_FILTER_TTY.
Referenced by roboptim::assertion_failed(), roboptim::assertion_failed_msg(), roboptim::detail::printConstraint< P >::operator()(), roboptim::SolverError::print(), and roboptim::Problem< T >::print().
std::ostream& roboptim::fg::resetfg (std::ostream & o) [inline]
Default foreground color.
References ROBOPTIM_CORE_FILTER_TTY.
std::ostream& roboptim::fg::warn (std::ostream & o) [inline]
References orange().
Referenced by roboptim::assertion_failed_msg(), and roboptim::Problem< T >::print().
std::ostream& roboptim::fg::yellow (std::ostream & o) [inline]
References ROBOPTIM_CORE_FILTER_TTY.