roboptim::visualization::matplotlib::detail Namespace Reference
roboptim::visualization::matplotlib::detail Namespace Reference
Functions
std::string set_red_white_blue_cmap ()
std::string set_red_yellow_blue_cmap ()
std::string dense_matrix_to_matplotlib (GenericFunctionTraits< EigenMatrixDense >::const_matrix_ref mat, MatrixPlotType::Type type)
std::string sparse_matrix_to_matplotlib (GenericFunctionTraits< EigenMatrixSparse >::const_matrix_ref mat, MatrixPlotType::Type type)
Function Documentation
std::string roboptim::visualization::matplotlib::detail::dense_matrix_to_matplotlib (GenericFunctionTraits< EigenMatrixDense >::const_matrix_ref mat, MatrixPlotType::Type type)
References roboptim::visualization::matplotlib::MatrixPlotType::Log, roboptim::normalize(), set_red_white_blue_cmap(), set_red_yellow_blue_cmap(), and roboptim::visualization::matplotlib::MatrixPlotType::Structure.
Referenced by roboptim::visualization::matplotlib::plot_mat().
std::string roboptim::visualization::matplotlib::detail::set_red_white_blue_cmap ()
Referenced by dense_matrix_to_matplotlib(), and sparse_matrix_to_matplotlib().
std::string roboptim::visualization::matplotlib::detail::set_red_yellow_blue_cmap ()
Referenced by dense_matrix_to_matplotlib(), and sparse_matrix_to_matplotlib().
std::string roboptim::visualization::matplotlib::detail::sparse_matrix_to_matplotlib (GenericFunctionTraits< EigenMatrixSparse >::const_matrix_ref mat, MatrixPlotType::Type type)
References roboptim::visualization::matplotlib::MatrixPlotType::Log, roboptim::normalize(), set_red_white_blue_cmap(), set_red_yellow_blue_cmap(), roboptim::StorageOrder, and roboptim::visualization::matplotlib::MatrixPlotType::Structure.
Referenced by roboptim::visualization::matplotlib::plot_mat().