Visualization
Visualization
Classes
class roboptim::visualization::gnuplot::Command
Gnuplot command.
class roboptim::visualization::Gnuplot
Gnuplot script.
class roboptim::visualization::matplotlib::Import
matplotlib import.
struct roboptim::visualization::matplotlib::MatrixPlotType
Wrap enum for matrix plotting type.
class roboptim::visualization::Matplotlib
matplotlib script
Typedefs
typedef
Function::discreteInterval_t roboptim::visualization::gnuplot::discreteInterval_t
Import discrete interval type from function.
typedef
Function::discreteInterval_t roboptim::visualization::matplotlib::discreteInterval_t
Import discrete interval type from function.
Functions
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::comment (const char *)
Make a Gnuplot comment.
template<typename T >
Command roboptim::visualization::gnuplot::comment (const T &content)
Make a Gnuplot comment.
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::set (const char *var, const char *val="")
Make a Gnuplot set command.
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::unset (const char *var)
Make a Gnuplot unset command.
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::show (const char *var)
Make a Gnuplot show command.
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::clear ()
Make a Gnuplot clear command.
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::pwd ()
Make a Gnuplot pwdcommand.
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::quit ()
Make a Gnuplot quit command.
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::replot ()
Make a Gnuplot replot command.
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::reread ()
Make a Gnuplot reread command.
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::reset ()
Make a Gnuplot reset command.
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::cd (const char *dir)
Make a Gnuplot cd command.
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::help (const char *topic="")
Make a Gnuplot help command.
template<typename T >
Command roboptim::visualization::gnuplot::plot_jac (const GenericDifferentiableFunction< T > &f, typename GenericDifferentiableFunction< T >::const_argument_ref arg)
Plot the Jacobian structure with Gnuplot.
template<>
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::plot_jac (const DifferentiableFunction &f, DifferentiableFunction::const_argument_ref arg)
template<>
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::plot_jac (const DifferentiableSparseFunction &f, DifferentiableSparseFunction::const_argument_ref arg)
template<typename T >
Command roboptim::visualization::gnuplot::plot (const GenericFunction< T > &f, discreteInterval_t interval)
Plot a 1D function with Gnuplot.
template<typename T >
Command roboptim::visualization::gnuplot::plot_xy (const GenericFunction< T > &f, discreteInterval_t interval)
Plot a 2D function with Gnuplot.
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::plot_mat (GenericFunctionTraits< EigenMatrixDense >::const_matrix_ref mat)
Plot the structure of a matrix with Gnuplot.
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::plot_mat (GenericFunctionTraits< EigenMatrixSparse >::const_matrix_ref mat)
template<typename T >
Gnuplot & roboptim::visualization::operator<< (Gnuplot &gp, T t)
Override operator<< to handle Gnuplot command insertion.
ROBOPTIM_DLLAPI Import roboptim::visualization::matplotlib::import (const std::string &packages)
Import function that follows the style of commands.
ROBOPTIM_DLLAPI Import roboptim::visualization::matplotlib::import (const std::string &from, const std::string &packages)
Import function that follows the style of commands.
ROBOPTIM_DLLAPI Command roboptim::visualization::matplotlib::comment (const char *)
Make a matplotlib comment.
template<typename T >
Command roboptim::visualization::matplotlib::comment (const T &content)
Make a matplotlib comment.
ROBOPTIM_DLLAPI Command roboptim::visualization::matplotlib::set (const char *var, const char *val)
Make a matplotlib set command.
ROBOPTIM_DLLAPI Command roboptim::visualization::matplotlib::show ()
ROBOPTIM_DLLAPI Command roboptim::visualization::matplotlib::figure ()
ROBOPTIM_DLLAPI Command roboptim::visualization::matplotlib::title (const char *argument)
template<typename T >
Command roboptim::visualization::matplotlib::plot (const GenericFunction< T > &f, discreteInterval_t interval)
Plot a 1D function with matplotlib.
ROBOPTIM_DLLAPI Command roboptim::visualization::matplotlib::plot_mat (GenericFunctionTraits< EigenMatrixDense >::const_matrix_ref mat, MatrixPlotType::Type type=MatrixPlotType::Values)
Plot the structure of a matrix with matplotlib.
ROBOPTIM_DLLAPI Command roboptim::visualization::matplotlib::plot_mat (GenericFunctionTraits< EigenMatrixSparse >::const_matrix_ref mat, MatrixPlotType::Type type=MatrixPlotType::Values)
template<typename T >
Command roboptim::visualization::matplotlib::plot_mat (typename GenericFunctionTraits< T >::const_matrix_ref, MatrixPlotType::Type=MatrixPlotType::Values)
template<typename T >
Matplotlib & roboptim::visualization::operator<< (Matplotlib &ml, T t)
Override operator<< to handle matplotlib command insertion.
Variables
template<typename T >
Command roboptim::visualization::gnuplot::plot_mat (typename GenericFunctionTraits< T >::const_matrix_ref)
Detailed Description
Typedef Documentation
typedef Function::discreteInterval_t roboptim::visualization::gnuplot::discreteInterval_t
Import discrete interval type from function.
typedef Function::discreteInterval_t roboptim::visualization::matplotlib::discreteInterval_t
Import discrete interval type from function.
Function Documentation
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::cd (const char * dir)
Make a Gnuplot cd command.
Make a Gnuplot cd command (change current directory).
Parameters
dir new directory
Returns
Gnuplot command
Examples:
visualization-gnuplot-simple.cc.
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::clear ()
Make a Gnuplot clear command.
Make a Gnuplot clear command (clear the screen).
Returns
Gnuplot command
Examples:
visualization-gnuplot-simple.cc.
Command roboptim::visualization::gnuplot::comment (const char * content)
Make a Gnuplot comment.
Exceptions
std::runtime_error
Examples:
visualization-gnuplot-function.cc, and visualization-gnuplot-simple.cc.
Referenced by roboptim::visualization::gnuplot::comment(), and roboptim::visualization::Gnuplot::Gnuplot().
template<typename T > Command roboptim::visualization::gnuplot::comment (const T & content) inline
Make a Gnuplot comment.
Exceptions
std::runtime_error
References roboptim::visualization::gnuplot::comment().
Command roboptim::visualization::matplotlib::comment (const char * content)
Make a matplotlib comment.
Exceptions
std::runtime_error
Examples:
visualization-matplotlib-function.cc, and visualization-matplotlib-simple.cc.
Referenced by roboptim::visualization::matplotlib::comment().
template<typename T > Command roboptim::visualization::matplotlib::comment (const T & content) inline
Make a matplotlib comment.
Exceptions
std::runtime_error
References roboptim::visualization::matplotlib::comment().
ROBOPTIM_DLLAPI Command roboptim::visualization::matplotlib::figure ()
Examples:
visualization-matplotlib-simple.cc.
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::help (const char * topic = "")
Make a Gnuplot help command.
Make a Gnuplot help command (display Gnuplot help).
Parameters
topic help topic
Returns
Gnuplot command
Examples:
visualization-gnuplot-simple.cc.
Import roboptim::visualization::matplotlib::import (const std::string & packages)
Import function that follows the style of commands.
Import roboptim::visualization::matplotlib::import (const std::string & from, const std::string & packages)
Import function that follows the style of commands.
template<typename T > Gnuplot& roboptim::visualization::operator<< (Gnuplot & gp, T t)
Override operator<< to handle Gnuplot command insertion.
Template Parameters
Gnuplot command type
Parameters
gp Gnuplot script that will receive the new command
t new Gnuplot command.
Returns
modified Gnuplot script
References roboptim::visualization::Gnuplot::push_command().
template<typename T > Matplotlib& roboptim::visualization::operator<< (Matplotlib & ml, T t)
Override operator<< to handle matplotlib command insertion.
Template Parameters
Matplotlib command type
Parameters
gp matplotlib script that will receive the new command
t new matplotlib command.
Returns
modified matplotlib script
References roboptim::visualization::Matplotlib::push_command().
template<typename T > Command roboptim::visualization::gnuplot::plot (const GenericFunction< T > & f, discreteInterval_t interval)
Plot a 1D function with Gnuplot.
Plot a 1D function in Gnuplot on a specific interval. X axis is the function's argument, Y axis is result.
Parameters
f function to be plotted
interval plot interval
Returns
Gnuplot command
Examples:
visualization-gnuplot-function.cc.
References roboptim::GenericFunction< T >::getName(), roboptim::GenericFunction< T >::inputSize(), roboptim::normalize(), and roboptim::GenericFunction< T >::outputSize().
template<typename T > Command roboptim::visualization::matplotlib::plot (const GenericFunction< T > & f, discreteInterval_t interval)
Plot a 1D function with matplotlib.
Plot a 1D function in matplotlib on a specific interval. X axis is the function's argument, Y axis is result.
Parameters
f function to be plotted
interval plot interval
Returns
matplotlib command
Examples:
visualization-matplotlib-function.cc.
References roboptim::GenericFunction< T >::getName(), roboptim::GenericFunction< T >::inputSize(), roboptim::normalize(), and roboptim::GenericFunction< T >::outputSize().
template<typename T > Command roboptim::visualization::gnuplot::plot_jac (const GenericDifferentiableFunction< T > & f, typename GenericDifferentiableFunction< T >::const_argument_ref arg)
Plot the Jacobian structure with Gnuplot.
Plot the structure of the Jacobian of a differentiable function with Gnuplot. Nonzero values will be displayed in blue, zeros in white.
When dealing with a dense matrix, the actual values are printed and exact zeros will be displayed in white.
When dealing with a sparse matrix, inserted zeros will also be treated as nonzero values, thus returning the real structure of the sparse Jacobian matrix. In this case, the values returned are 1 for sparse elements, and 0 for actual zeros.
Parameters
f differentiable function whose Jacobian will be plotted
arg optimization parameters of the point to plot. This parameter is not relevant when dealing with sparse functions, since it should not change the Jacobian's sparse structure.
Returns
Gnuplot command
template<> ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::plot_jac (const DifferentiableFunction & f, DifferentiableFunction::const_argument_ref arg)
References roboptim::visualization::gnuplot::detail::dense_jacobian_to_gnuplot(), roboptim::GenericFunction< T >::getName(), and roboptim::GenericDifferentiableFunction< T >::jacobian().
template<> ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::plot_jac (const DifferentiableSparseFunction & f, DifferentiableSparseFunction::const_argument_ref arg)
References roboptim::GenericFunction< T >::getName(), roboptim::GenericDifferentiableFunction< T >::jacobian(), and roboptim::visualization::gnuplot::detail::sparse_jacobian_to_gnuplot().
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::plot_mat (GenericFunctionTraits< EigenMatrixDense >::const_matrix_ref mat)
Plot the structure of a matrix with Gnuplot.
Plot the structure of a matrix with Gnuplot. Nonzero values will be displayed in blue, zeros in white.
When dealing with a dense matrix, the actual values are printed and exact zeros will be displayed in white.
When dealing with a sparse matrix, inserted zeros will also be treated as nonzero values, thus returning the real structure of the sparse matrix. In this case, the values returned are 1 for sparse elements, and 0 for actual zeros.
Parameters
mat matrix to plot.
Returns
Gnuplot command.
References roboptim::visualization::gnuplot::detail::dense_matrix_to_gnuplot().
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::plot_mat (GenericFunctionTraits< EigenMatrixSparse >::const_matrix_ref mat)
References roboptim::visualization::gnuplot::detail::sparse_matrix_to_gnuplot().
Command roboptim::visualization::matplotlib::plot_mat (GenericFunctionTraits< EigenMatrixDense >::const_matrix_ref mat, MatrixPlotType::Type type = MatrixPlotType::Values)
Plot the structure of a matrix with matplotlib.
Plot the structure of a matrix with matplotlib. Nonzero values will be displayed in blue, zeros in white.
When dealing with a dense matrix, the actual values are printed and exact zeros will be displayed in white.
When dealing with a sparse matrix, inserted zeros will also be treated as nonzero values, thus returning the real structure of the sparse matrix. In this case, the values returned are 1 for sparse elements, and 0 for actual zeros.
Parameters
mat matrix to plot.
type type of plotting for the matrix.
Returns
Gnuplot command.
References roboptim::visualization::matplotlib::detail::dense_matrix_to_matplotlib().
Command roboptim::visualization::matplotlib::plot_mat (GenericFunctionTraits< EigenMatrixSparse >::const_matrix_ref mat, MatrixPlotType::Type type = MatrixPlotType::Values)
References roboptim::visualization::matplotlib::detail::sparse_matrix_to_matplotlib().
template<typename T > Command roboptim::visualization::matplotlib::plot_mat (typename GenericFunctionTraits< T >::const_matrix_ref , MatrixPlotType::Type = MatrixPlotType::Values)
template<typename T > Command roboptim::visualization::gnuplot::plot_xy (const GenericFunction< T > & f, discreteInterval_t interval)
Plot a 2D function with Gnuplot.
Plot a 2D function in Gnuplot on a specific interval. X and Y axises are the function result, the original arguments are not displayed.
Parameters
f function to be plotted
interval plot interval
Returns
Gnuplot command
Examples:
visualization-gnuplot-function.cc.
References roboptim::GenericFunction< T >::getName(), roboptim::GenericFunction< T >::inputSize(), roboptim::normalize(), and roboptim::GenericFunction< T >::outputSize().
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::pwd ()
Make a Gnuplot pwdcommand.
Make a Gnuplot pwd command (show the current directory).
Returns
Gnuplot command
Examples:
visualization-gnuplot-simple.cc.
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::quit ()
Make a Gnuplot quit command.
Make a Gnuplot quit command (quit Gnuplot).
Returns
Gnuplot command
Examples:
visualization-gnuplot-simple.cc.
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::replot ()
Make a Gnuplot replot command.
Make a Gnuplot replot command (redraw previously defined curves).
Returns
Gnuplot command
Examples:
visualization-gnuplot-simple.cc.
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::reread ()
Make a Gnuplot reread command.
Make a Gnuplot reread command (reread data files).
Returns
Gnuplot command
Examples:
visualization-gnuplot-simple.cc.
ROBOPTIM_DLLAPI Command roboptim::visualization::gnuplot::reset ()
Make a Gnuplot reset command.
Make a Gnuplot replot command (reset Gnuplot state).
Returns
Gnuplot command
Examples:
visualization-gnuplot-simple.cc.
Command roboptim::visualization::gnuplot::set (const char * var, const char * val = "")
Make a Gnuplot set command.
Make a Gnuplot set command (assign a new value to a variable in Gnuplot).
Parameters
var variable that will be set
val new variable value
Returns
Gnuplot command
Examples:
visualization-gnuplot-function.cc, and visualization-gnuplot-simple.cc.
Referenced by roboptim::visualization::Gnuplot::make_interactive_gnuplot().
Command roboptim::visualization::matplotlib::set (const char * var, const char * val)
Make a matplotlib set command.
Make a matplotlib set command (assign a new value to a variable in matplotlib).
Parameters
var variable that will be set
val new variable value
Returns
matplotlib command
Examples:
visualization-matplotlib-simple.cc.
Command roboptim::visualization::gnuplot::show (const char * var)
Make a Gnuplot show command.
Make a Gnuplot show command (show a variable value).
Parameters
var variable that will be shown
Returns
Gnuplot command
Examples:
visualization-gnuplot-simple.cc.
ROBOPTIM_DLLAPI Command roboptim::visualization::matplotlib::show ()
Examples:
visualization-matplotlib-simple.cc.
ROBOPTIM_DLLAPI Command roboptim::visualization::matplotlib::title (const char * argument)
Command roboptim::visualization::gnuplot::unset (const char * var)
Make a Gnuplot unset command.
Make a Gnuplot unset command (destroy a variable).
Parameters
var variable that will be unset
Returns
Gnuplot command
Examples:
visualization-gnuplot-function.cc.
Variable Documentation
template<typename T > Command roboptim::visualization::gnuplot::plot_mat
Referenced by roboptim::visualization::gnuplot::detail::dense_jacobian_to_gnuplot(), and roboptim::visualization::gnuplot::detail::sparse_jacobian_to_gnuplot().