Function operators
Function operators
Classes
class roboptim::Bind< U >
Bind some function input to a constant value.
class roboptim::Chain< U, V >
Chain two RobOptim functions.
class roboptim::Concatenate< U >
Concatenate the output of two functions.
class roboptim::Derivative< U >
Return the derivative of a function w.r.t.
class roboptim::Map< U >
Apply a function several times to an input vector.
class roboptim::Minus< U, V >
Subtract two RobOptim functions.
class roboptim::Plus< U, V >
Sum two RobOptim functions.
class roboptim::Product< U, V >
Product of two RobOptim functions.
class roboptim::Scalar< U >
Multiply by a constant scalar value.
class roboptim::SelectionById< U >
Select part of a function.
class roboptim::Selection< U >
Select a block of a function's output.
class roboptim::Split< T >
Select an element of a function's output.
Functions
template<typename U >
boost::shared_ptr< Bind< U > > roboptim::bind (boost::shared_ptr< U > origin, const typename Bind< U >::boundValues_t &boundValues)
template<typename U , typename V >
boost::shared_ptr< Chain< U, V > > roboptim::chain (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
Chain two RobOptim functions.
template<typename U , typename V >
boost::shared_ptr< Concatenate
< typename
detail::PromoteTrait< U, V >
::T_promote > > roboptim::concatenate (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U >
boost::shared_ptr< Derivative
< U > > roboptim::derivative (boost::shared_ptr< U > origin, typename Derivative< U >::size_type variableId=0)
template<typename U >
boost::shared_ptr< Map< U > > roboptim::map (boost::shared_ptr< U > origin, typename U::size_type repeat)
template<typename U , typename V >
boost::shared_ptr< Minus< U, V > > roboptim::minus (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U , typename V >
boost::shared_ptr< Minus< U, V > > roboptim::operator- (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U , typename V >
boost::shared_ptr< Plus< U, V > > roboptim::plus (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U , typename V >
boost::shared_ptr< Plus< U, V > > roboptim::operator+ (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U , typename V >
boost::shared_ptr< Product< U,
V > > roboptim::product (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U , typename V >
boost::shared_ptr< Product< U,
V > > roboptim::operator* (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U >
boost::shared_ptr< Scalar< U > > roboptim::scalar (boost::shared_ptr< U > origin, typename Scalar< U >::size_type start=0, typename Scalar< U >::size_type size=1)
template<typename U >
boost::shared_ptr< Scalar< U > > roboptim::operator* (typename Scalar< U >::value_type scalar, boost::shared_ptr< U > origin)
template<typename U >
boost::shared_ptr< Scalar< U > > roboptim::operator* (boost::shared_ptr< U > origin, typename Scalar< U >::value_type scalar)
template<typename U >
boost::shared_ptr< U > roboptim::operator+ (boost::shared_ptr< U > origin)
template<typename U >
boost::shared_ptr< Scalar< U > > roboptim::operator- (boost::shared_ptr< U > origin)
template<typename U >
boost::shared_ptr
< SelectionById< U > > roboptim::selectionById (boost::shared_ptr< U > origin, std::vector< bool > selector)
template<typename U >
boost::shared_ptr< Selection< U > > roboptim::selection (boost::shared_ptr< U > origin, typename Selection< U >::size_type start=0, typename Selection< U >::size_type size=1)
template<typename P , typename C >
void roboptim::addNonScalarConstraint (P &problem, boost::shared_ptr< C > constraint, std::vector< Function::interval_t > interval, std::vector< Function::value_type > scale=std::vector< Function::value_type >())
Detailed Description
Function Documentation
template<typename P , typename C > void roboptim::addNonScalarConstraint (P & problem, boost::shared_ptr< C > constraint, std::vector< Function::interval_t > interval, std::vector< Function::value_type > scale = std::vector<Function::value_type> ())
References roboptim::split().
template<typename U > boost::shared_ptr<Bind<U> > roboptim::bind (boost::shared_ptr< U > origin, const typename Bind< U >::boundValues_t & boundValues)
Referenced by roboptim::callback::Multiplexer< S >::attach(), and roboptim::SolverCallback< S >::callback().
template<typename U , typename V > boost::shared_ptr<Chain<U, V> > roboptim::chain (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
Chain two RobOptim functions.
This will instantiate a Chain<U,V> RobOptim operator that will realize the underlying computations.
template<typename U , typename V > boost::shared_ptr<Concatenate<typename detail::PromoteTrait<U, V>::T_promote > > roboptim::concatenate (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U > boost::shared_ptr<Derivative<U> > roboptim::derivative (boost::shared_ptr< U > origin, typename Derivative< U >::size_type variableId = 0)
Referenced by roboptim::CachedFunction< T >::cachedFunctionDerivative(), roboptim::NTimesDerivableFunction< 2 >::derivative(), roboptim::CachedFunction< T >::impl_derivative(), roboptim::NTimesDerivableFunction< 2 >::impl_gradient(), and roboptim::NTimesDerivableFunction< 2 >::impl_hessian().
template<typename U > boost::shared_ptr<Map<U> > roboptim::map (boost::shared_ptr< U > origin, typename U::size_type repeat)
template<typename U , typename V > boost::shared_ptr<Minus<U, V> > roboptim::minus (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U , typename V > boost::shared_ptr<Product<U, V> > roboptim::operator* (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U > boost::shared_ptr<Scalar<U> > roboptim::operator* (typename Scalar< U >::value_type scalar, boost::shared_ptr< U > origin)
References roboptim::scalar().
template<typename U > boost::shared_ptr<Scalar<U> > roboptim::operator* (boost::shared_ptr< U > origin, typename Scalar< U >::value_type scalar)
References roboptim::scalar().
template<typename U , typename V > boost::shared_ptr<Plus<U, V> > roboptim::operator+ (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U > boost::shared_ptr<U> roboptim::operator+ (boost::shared_ptr< U > origin)
template<typename U , typename V > boost::shared_ptr<Minus<U, V> > roboptim::operator- (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U > boost::shared_ptr<Scalar<U> > roboptim::operator- (boost::shared_ptr< U > origin)
template<typename U , typename V > boost::shared_ptr<Plus<U, V> > roboptim::plus (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U , typename V > boost::shared_ptr<Product<U, V> > roboptim::product (boost::shared_ptr< U > left, boost::shared_ptr< V > right)
template<typename U > boost::shared_ptr<Scalar<U> > roboptim::scalar (boost::shared_ptr< U > origin, typename Scalar< U >::size_type start = 0, typename Scalar< U >::size_type size = 1)
Referenced by roboptim::operator*().
template<typename U > boost::shared_ptr<Selection<U> > roboptim::selection (boost::shared_ptr< U > origin, typename Selection< U >::size_type start = 0, typename Selection< U >::size_type size = 1)
template<typename U > boost::shared_ptr<SelectionById<U> > roboptim::selectionById (boost::shared_ptr< U > origin, std::vector< bool > selector)