Function decorators
Function decorators
Namespaces
roboptim::finiteDifferenceGradientPolicies
Contains finite difference gradients policies.
Classes
class roboptim::CachedFunction< T >
Store previous function computation.
class roboptim::BadGradient< T >
Exception thrown when a gradient check fails.
class roboptim::BadJacobian< T >
Exception thrown when a Jacobian check fails.
class roboptim::GenericFiniteDifferenceGradient< T, FdgPolicy >
Compute automatically a gradient with finite differences.
Functions
template<typename T >
std::ostream & roboptim::operator<< (std::ostream &o, const BadGradient< T > &f)
Override operator<< to handle exception display.
template<typename T >
std::ostream & roboptim::operator<< (std::ostream &o, const BadJacobian< T > &f)
Override operator<< to handle exception display.
template<typename T >
bool roboptim::checkGradient (const GenericDifferentiableFunction< T > &function, typename GenericDifferentiableFunction< T >::size_type functionId, typename GenericDifferentiableFunction< T >::const_argument_ref x, typename GenericDifferentiableFunction< T >::value_type threshold=finiteDifferenceThreshold)
Check if a gradient is valid.
template<typename T >
void roboptim::checkGradientAndThrow (const GenericDifferentiableFunction< T > &function, typename GenericDifferentiableFunction< T >::size_type functionId, typename GenericDifferentiableFunction< T >::const_argument_ref x, typename GenericDifferentiableFunction< T >::value_type threshold=finiteDifferenceThreshold) throw (BadGradient<T>)
template<typename T >
bool roboptim::checkJacobian (const GenericDifferentiableFunction< T > &function, typename GenericDifferentiableFunction< T >::const_argument_ref x, typename GenericDifferentiableFunction< T >::value_type threshold=finiteDifferenceThreshold)
Check if a Jacobian is valid.
template<typename T >
void roboptim::checkJacobianAndThrow (const GenericDifferentiableFunction< T > &function, typename GenericDifferentiableFunction< T >::const_argument_ref x, typename GenericDifferentiableFunction< T >::value_type threshold=finiteDifferenceThreshold) throw (BadJacobian<T>)
Variables
static const double roboptim::finiteDifferenceThreshold = 1e-4
Default threshold for checkGradient.
static const double roboptim::finiteDifferenceEpsilon = 1e-8
Default epsilon for finite difference class.
Detailed Description
Function Documentation
template<typename T > bool roboptim::checkGradient (const GenericDifferentiableFunction< T > & function, typename GenericDifferentiableFunction< T >::size_type functionId, typename GenericDifferentiableFunction< T >::const_argument_ref x, typename GenericDifferentiableFunction< T >::value_type threshold = finiteDifferenceThreshold)
Check if a gradient is valid.
Check if a gradient is valid by comparing the distance between its gradient and an automatically computed finite differences gradient.
Parameters
function function that will be checked
functionId function id in split representation
x point where the gradient will be evaluated
threshold maximum tolerated error
Returns
true if valid, false if not
Examples:
numeric-quadratic-function.cc.
References roboptim::allclose(), roboptim::GenericDifferentiableFunction< T >::gradient(), ROBOPTIM_ALLOW_DEPRECATED_OFF, and ROBOPTIM_ALLOW_DEPRECATED_ON.
Referenced by roboptim::checkGradientAndThrow().
template<typename T > void roboptim::checkGradientAndThrow (const GenericDifferentiableFunction< T > & function, typename GenericDifferentiableFunction< T >::size_type functionId, typename GenericDifferentiableFunction< T >::const_argument_ref x, typename GenericDifferentiableFunction< T >::value_type threshold = finiteDifferenceThreshold) throw (BadGradient< T >)
References roboptim::checkGradient(), roboptim::GenericDifferentiableFunction< T >::gradient(), ROBOPTIM_ALLOW_DEPRECATED_OFF, and ROBOPTIM_ALLOW_DEPRECATED_ON.
template<typename T > bool roboptim::checkJacobian (const GenericDifferentiableFunction< T > & function, typename GenericDifferentiableFunction< T >::const_argument_ref x, typename GenericDifferentiableFunction< T >::value_type threshold = finiteDifferenceThreshold)
Check if a Jacobian is valid.
Check if a Jacobian is valid by comparing the distance between the matrix and an automatically computed finite differences Jacobian.
Parameters
function function that will be checked
x point where the Jacobian will be evaluated
threshold maximum tolerated error
Returns
true if valid, false if not
Examples:
numeric-quadratic-function.cc.
References roboptim::allclose(), roboptim::GenericDifferentiableFunction< T >::jacobian(), ROBOPTIM_ALLOW_DEPRECATED_OFF, and ROBOPTIM_ALLOW_DEPRECATED_ON.
Referenced by roboptim::checkJacobianAndThrow().
template<typename T > void roboptim::checkJacobianAndThrow (const GenericDifferentiableFunction< T > & function, typename GenericDifferentiableFunction< T >::const_argument_ref x, typename GenericDifferentiableFunction< T >::value_type threshold = finiteDifferenceThreshold) throw (BadJacobian< T >)
References roboptim::checkJacobian(), roboptim::GenericDifferentiableFunction< T >::jacobian(), ROBOPTIM_ALLOW_DEPRECATED_OFF, and ROBOPTIM_ALLOW_DEPRECATED_ON.
template<typename T > std::ostream & roboptim::operator<< (std::ostream & o, const BadGradient< T > & f)
Override operator<< to handle exception display.
Parameters
o output stream used for display
f function to be displayed
Returns
output stream
template<typename T > std::ostream & roboptim::operator<< (std::ostream & o, const BadJacobian< T > & f)
Override operator<< to handle exception display.
Parameters
o output stream used for display
f function to be displayed
Returns
output stream
Variable Documentation
const double roboptim::finiteDifferenceEpsilon = 1e-8 static
Default epsilon for finite difference class.
const double roboptim::finiteDifferenceThreshold = 1e-4 static
Default threshold for checkGradient.