roboptim::visualization::gnuplot::detail Namespace Reference
roboptim::visualization::gnuplot::detail Namespace Reference
Functions
std::string dense_jacobian_to_gnuplot (DifferentiableFunction::const_jacobian_ref jac, const std::string &name)
std::string sparse_jacobian_to_gnuplot (DifferentiableSparseFunction::const_jacobian_ref jac, const std::string &name)
template<typename T >
void set_matrix_header (std::string &str, typename GenericFunctionTraits< T >::const_matrix_ref mat)
std::string dense_matrix_to_gnuplot (GenericFunctionTraits< EigenMatrixDense >::const_matrix_ref mat)
std::string sparse_matrix_to_gnuplot (GenericFunctionTraits< EigenMatrixSparse >::const_matrix_ref mat)
Function Documentation
std::string roboptim::visualization::gnuplot::detail::dense_jacobian_to_gnuplot (DifferentiableFunction::const_jacobian_ref jac, const std::string & name)
References roboptim::visualization::gnuplot::Command::command(), and roboptim::visualization::gnuplot::plot_mat.
Referenced by roboptim::visualization::gnuplot::plot_jac().
std::string roboptim::visualization::gnuplot::detail::dense_matrix_to_gnuplot (GenericFunctionTraits< EigenMatrixDense >::const_matrix_ref mat)
References roboptim::normalize().
Referenced by roboptim::visualization::gnuplot::plot_mat(), and sparse_matrix_to_gnuplot().
template<typename T > void roboptim::visualization::gnuplot::detail::set_matrix_header (std::string & str, typename GenericFunctionTraits< T >::const_matrix_ref mat)
std::string roboptim::visualization::gnuplot::detail::sparse_jacobian_to_gnuplot (DifferentiableSparseFunction::const_jacobian_ref jac, const std::string & name)
References roboptim::visualization::gnuplot::Command::command(), and roboptim::visualization::gnuplot::plot_mat.
Referenced by roboptim::visualization::gnuplot::plot_jac().
std::string roboptim::visualization::gnuplot::detail::sparse_matrix_to_gnuplot (GenericFunctionTraits< EigenMatrixSparse >::const_matrix_ref mat)
References dense_matrix_to_gnuplot().
Referenced by roboptim::visualization::gnuplot::plot_mat().