#!/bin/sh
set -ev

# Directories.
root_dir=`pwd`
build_dir="/tmp/_travis/build"
install_dir="/tmp/_travis/install"

if [ -d debian ]; then
    export GNUPGHOME="$root_dir/.travis/.gnupg"
    # If the build is a success, upload the source package to Launchpad.
    dput ppa:roboptim/ppa "$build_dir"/export/roboptim-core_*_source.changes
else
    coveralls						\
	-e _travis/install				\
	-e _travis/build/eigen-eigen-ffa86ffb5570/	\
	-e tests
    git remote set-url origin \
	https://thomas-moulard:${GH_TOKEN}@github.com/roboptim/roboptim-core.git
    git fetch origin gh-pages:gh-pages
    cd _travis/build/doc && ../../../cmake/github/update-doxygen-doc.sh
fi
